const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar,
		C3.Behaviors.Timer,
		C3.Behaviors.CV_BoundedDragnDrop,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.GD_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.Wait,
		C3.ScriptsInEvents.Gamees_Event27_Act2,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.ScriptsInEvents.Gamees_Event64_Act2,
		C3.ScriptsInEvents.Gamees_Event65_Act3,
		C3.ScriptsInEvents.Gamees_Event66_Act2,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.ScriptsInEvents.Gamees_Event75_Act1,
		C3.ScriptsInEvents.Gamees_Event76_Act1,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.ScriptsInEvents.Gamees_Event78_Act5,
		C3.ScriptsInEvents.Gamees_Event93_Act1,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.ScriptsInEvents.Gamees_Event97_Act1,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.Gamees_Event121_Act1,
		C3.ScriptsInEvents.Gamees_Event128_Act2,
		C3.ScriptsInEvents.Gamees_Event129_Act1,
		C3.ScriptsInEvents.Gamees_Event132_Act1,
		C3.ScriptsInEvents.Gamees_Event133_Act1,
		C3.ScriptsInEvents.Gamees_Event133_Act2,
		C3.ScriptsInEvents.Gamees_Event138_Act1,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.Stop,
		C3.ScriptsInEvents.Gamees_Event185_Act3,
		C3.ScriptsInEvents.Gamees_Event185_Act6,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.ScriptsInEvents.Gamees_Event200_Act3,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.ScriptsInEvents.Gamees_Event210_Act1,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar.Acts.SetValue,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.ScriptsInEvents.Gamees_Event225_Act1,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.AddChild,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Acts.RemoveFromParent,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Particles.Exps.Rate,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.CV_BoundedDragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Browser.Cnds.OnBackButton,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.Sprite.Exps.MeshRows,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.CV_BoundedDragnDrop.Acts.SetBoundY,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.viewporttop
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{PlayButton: 0},
	{FullscreenButton: 0},
	{Resign: 0},
	{Type: 0},
	{HomeButton: 0},
	{SoundButton: 0},
	{rvIcon: 0},
	{SoundButton2: 0},
	{isOpen: 0},
	{Tween: 0},
	{SideMenuBG: 0},
	{sideMenuButton: 0},
	{SM_FullscreenButton: 0},
	{SM_HomeButton: 0},
	{SM_SoundButton: 0},
	{SM_HomeButton2: 0},
	{PopUpBG: 0},
	{SplashBG: 0},
	{tweenToSizeX: 0},
	{tweenToSizeY: 0},
	{Logo: 0},
	{Fade: 0},
	{BlackScreen: 0},
	{BrandImage: 0},
	{boardPosition: 0},
	{Restart: 0},
	{winnerText: 0},
	{Mouse: 0},
	{difficultyText: 0},
	{Page: 0},
	{Number: 0},
	{SinglePlayer: 0},
	{"2player": 0},
	{InX: 0},
	{Sprite: 0},
	{CloseSM: 0},
	{WinnerBanner: 0},
	{CnnectFour: 0},
	{Restart2: 0},
	{index: 0},
	{backGround: 0},
	{onBoard: 0},
	{piece: 0},
	{errorText: 0},
	{newGame: 0},
	{Shop_Mask: 0},
	{Pin: 0},
	{ShopDecals: 0},
	{DecalsShopObject: 0},
	{open: 0},
	{InShop_Btn: 0},
	{ID: 0},
	{Shop_Buy_txt: 0},
	{ShopPieces: 0},
	{PiecesShopObject: 0},
	{ShopCollections: 0},
	{CollectionsShopObject: 0},
	{PiecesArray: 0},
	{DecalsArray: 0},
	{CollectionsArray: 0},
	{AJAX: 0},
	{Decal0: 0},
	{Undo: 0},
	{Skin0: 0},
	{ModeSelectDifficulties: 0},
	{Difiiculties: 0},
	{DPin: 0},
	{PlayB: 0},
	{GameBGPC: 0},
	{LogoBGLandscape: 0},
	{Sine: 0},
	{Sine2: 0},
	{LogoShineScreen: 0},
	{LogoBG: 0},
	{Tweenable: 0},
	{PiecesButton: 0},
	{DecalButton: 0},
	{CollectionsButton: 0},
	{Rotate: 0},
	{Shine: 0},
	{Particles: 0},
	{Particles2: 0},
	{EquipmentButtonsParticleScreen: 0},
	{SettingPopUp: 0},
	{VibrateOn: 0},
	{CloseSettings: 0},
	{Text: 0},
	{Asset2: 0},
	{Asset3: 0},
	{Asset4: 0},
	{HeadlineLandscape: 0},
	{TimeModlandscape: 0},
	{OriginX: 0},
	{TimeButton: 0},
	{CoinsLandscape: 0},
	{InfoButtonladnscape: 0},
	{Coins: 0},
	{ExtraCoins_: 0},
	{RadialBG: 0},
	{Radial: 0},
	{LeftHalf: 0},
	{Radial2: 0},
	{RightHalf: 0},
	{ShopDecals8: 0},
	{ShopDecals7: 0},
	{ShopDecals6: 0},
	{ShopDecals5: 0},
	{ShopDecals4: 0},
	{ShopDecals2: 0},
	{ShopDecals1: 0},
	{ShopDecals3: 0},
	{ShopDecals0: 0},
	{DecalPrice: 0},
	{PriceTag: 0},
	{TabsB: 0},
	{CollectionsTeblandscape: 0},
	{PiecesTablandscape: 0},
	{DecalsTablandscape: 0},
	{UsingFrameSmall: 0},
	{Price: 0},
	{BuyButtonLandscape: 0},
	{ShopPieces8: 0},
	{ShopPieces4: 0},
	{ShopPieces5: 0},
	{ShopPieces6: 0},
	{ShopPieces7: 0},
	{ShopPieces2: 0},
	{ShopPieces3: 0},
	{ShopPieces1: 0},
	{ShopPieces0: 0},
	{collectionsShop0: 0},
	{collectionsShop2: 0},
	{collectionsShop4: 0},
	{collectionsShop1: 0},
	{collectionsShop3: 0},
	{CollectionPrice: 0},
	{UsingFrameBig: 0},
	{PiecesPC: 0},
	{DecalsPC: 0},
	{CollectionsPC: 0},
	{CloseShopButton: 0},
	{TimeModePopUp: 0},
	{YesButtonlandscape: 0},
	{NoButtonlandscape: 0},
	{BoardPC: 0},
	{ChosenPiece: 0},
	{possibleMove: 0},
	{Player: 0},
	{PlayerHolder: 0},
	{Skin1: 0},
	{Skin2: 0},
	{Skin3: 0},
	{Skin4: 0},
	{Skin5: 0},
	{Skin6: 0},
	{Skin7: 0},
	{Skin8: 0},
	{Decal1: 0},
	{Decal2: 0},
	{Decal3: 0},
	{Decal4: 0},
	{Decal5: 0},
	{Decal6: 0},
	{Decal7: 0},
	{Decal8: 0},
	{KeepPlayingPopUp: 0},
	{KeepPlayingButtonlandscape: 0},
	{LoseTextlandscape: 0},
	{ResignButtonlandscape_: 0},
	{EatenCount: 0},
	{TimeDotsHolder: 0},
	{Dotlandscape: 0},
	{Avatar: 0},
	{FastRadialProgressBar: 0},
	{Timer: 0},
	{AvatarTimer: 0},
	{Collection2: 0},
	{Collection0: 0},
	{Collection1: 0},
	{Collection3: 0},
	{Collection4: 0},
	{Difficulty: 0},
	{hard: 0},
	{med: 0},
	{Diff: 0},
	{CoinsWon: 0},
	{PopUpShineScreenlandscape: 0},
	{CoinsShineScreenlandscape: 0},
	{Text2: 0},
	{TopUIBar: 0},
	{LogoBGHome: 0},
	{PlayButtonsShine: 0},
	{CollectionsMobile: 0},
	{PiecesMobile: 0},
	{DecalsMobile: 0},
	{BoundedDragDrop: 0},
	{Sprite2: 0},
	{GameBGMobile: 0},
	{Vibration: 0},
	{Rules: 0},
	{CloseInfo: 0},
	{Iinital_size: 0},
	{Eatting_effect: 0},
	{Eatting_effect2: 0},
	{ScrollBG: 0},
	{ScrollTab: 0},
	{MyRuller: 0},
	{Asset5: 0},
	{Asset6: 0},
	{Asset7: 0},
	{NoCoins: 0},
	{NoMoves: 0},
	{"30TurnsDraw": 0},
	{chet: 0},
	{PopUpShineScreenlandscape2: 0},
	{Untitled: 0},
	{Anchor: 0},
	{test: 0},
	{home: 0},
	{Fade2: 0},
	{FXCoin: 0},
	{CoinExplo: 0},
	{DoubleCoinsButton: 0},
	{isTotal: 0},
	{ExtraTimeText: 0},
	{PiecesRewardText: 0},
	{KingsBonus: 0},
	{AteKingsBonus: 0},
	{KingTakesBonus: 0},
	{DoublesBonus: 0},
	{TripleBonus: 0},
	{Amount: 0},
	{CurrentAmount: 0},
	{RewardAmount: 0},
	{DefficultyBonusText: 0},
	{TotalCoinsReward: 0},
	{Coin: 0},
	{LoadingBar: 0},
	{TiledBackground: 0},
	{RewardsScreen: 0},
	{TempArray: 0},
	{ButtonsSpawner: 0},
	{Store: 0},
	{Restart3: 0},
	{RewardCoins: 0},
	{StatsTitle: 0},
	{StatsPanelLine: 0},
	{StatsTitle2: 0},
	{NotEnoughCoins: 0},
	{NoWifi: 0},
	{Mask: 0},
	{Asset: 0},
	{GameDistributionSDK: 0},
	{Blackscreen_Rotate: 0},
	{RotateScreen: 0},
	{Message: 0},
	{GlobalButtons: 0},
	{FullScreenButtons: 0},
	{HomeButtons: 0},
	{SoundButtons: 0},
	{ModeSelectTweens: 0},
	{Buttons: 0},
	{DecalsSkins: 0},
	{PiecesSkins: 0},
	{Settings: 0},
	{DecalsShop: 0},
	{PiecesShop: 0},
	{CollectionsShop: 0},
	{ShopSpawners: 0},
	{ShopHolders: 0},
	{ShopPageSelection: 0},
	{CollectionSkins: 0},
	{Difficulties: 0},
	{VibrateButtons: 0},
	{GameBGS: 0},
	{RadialTeam: 0},
	{CanTouch: 0},
	{Tween2: 0},
	{BouncyBois: 0},
	{FadeTexts: 0},
	{isGameOver: 0},
	{GameRunning: 0},
	{onComputerTurn: 0},
	{level: 0},
	{PlayerTurn: 0},
	{NoMoveDraw: 0},
	{playingVsComputer: 0},
	{DecalSkin: 0},
	{PieceSkin: 0},
	{CollectionSkin: 0},
	{BGColor: 0},
	{PlayersSwaped: 0},
	{isEven: 0},
	{x: 0},
	{y: 0},
	{width: 0},
	{height: 0},
	{color: 0},
	{IsKing: 0},
	{pieceIndex: 0},
	{StepCounter: 0},
	{movingPiece: 0},
	{eatenPiece: 0},
	{promote: 0},
	{MovesPossible: 0},
	{backgroundIndex: 0},
	{text: 0},
	{frame: 0},
	{PlayerWon: 0},
	{message: 0},
	{TurnTime: 0},
	{P0Strikes: 0},
	{P1Strikes: 0},
	{P0Avatar: 0},
	{P1Avatar: 0},
	{Winner: 0},
	{P0PiecesEaten: 0},
	{P1PiecesEaten: 0},
	{KingsMadeCounter: 0},
	{DoubleEatsCounter: 0},
	{TripleEatsCounter: 0},
	{EatenKingsCounter: 0},
	{KingEatCounter: 0},
	{WinTime: 0},
	{MoneyFromPieces: 0},
	{MoneyFromKings: 0},
	{MoneyFromTime: 0},
	{MoneyFromDoubles: 0},
	{MoneyFromTriple: 0},
	{MoneyFromEatenKings: 0},
	{MoneyFromKingEat: 0},
	{MoneyFromDifficulty: 0},
	{UsedDoubleCoins: 0},
	{RewardTextYOffset: 0},
	{RewardTextXOffset: 0},
	{MoneyPerPiece: 0},
	{MoneyPerKing: 0},
	{MoneyPerSecond: 0},
	{MoneyPerDouble: 0},
	{MoneyPerTriple: 0},
	{MoneyPerEatenKing: 0},
	{MoneyPerKingEat: 0},
	{MaxSecForMoney: 0},
	{PC_Scale: 0},
	{PC_offset: 0},
	{Height: 0},
	{Y: 0},
	{CountRewardsForSize: 0},
	{SOUND_ON: 0},
	{RandomMove: 0},
	{SFX_Type: 0},
	{IsFullScreenAllowed: 0},
	{IsAdsAllowed: 0},
	{IsAdmobDone: 0},
	{GoogleAd: 0},
	{GoogleAd_timeLimit: 0},
	{FreeAd: 0},
	{PiecesExists: 0},
	{DecalsExists: 0},
	{CollectionsExist: 0},
	{Local_ID: 0},
	{Platform: 0},
	{ExportVersion: 0},
	{RV_type: 0},
	{first_set: 0},
	{ADS: 0},
	{RV_ready: 0},
	{RV_play: 0},
	{RV_create_attempts: 0},
	{PlayedAd: 0},
	{TimeBetweenInterstitials: 0},
	{interstitialCooldown: 0},
	{type: 0},
	{CoinsAmount: 0},
	{X: 0},
	{Layer: 0},
	{Vibrate: 0},
	{destroy_fullscreen: 0},
	{ResignType: 0},
	{Frame: 0},
	{RadialMax: 0},
	{CurrentScore: 0},
	{MaxScore: 0},
	{RVCoinsCycleTime: 0},
	{RVCoinsCurrentTime: 0},
	{RVCoinsAddition: 0},
	{RowsAndColums: 0},
	{TimeMod: 0},
	{CurrentPage: 0},
	{offset: 0},
	{MenuSettingOpen: 0},
	{ShopOpen: 0},
	{IsCollection: 0},
	{DecalsPriceYoffset: 0},
	{DecalsBuyButtonYOffset: 0},
	{PiecesPriceYoffset: 0},
	{PiecesBuyButtonYOffset: 0},
	{CollectionsPriceYoffset: 0},
	{CollectionsBuyButtonYOffset: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	FullscreenButton: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	rvIcon: class extends self.ISpriteInstance {},
	SoundButton2: class extends self.ISpriteInstance {},
	SideMenuBG: class extends self.ISpriteInstance {},
	sideMenuButton: class extends self.ISpriteInstance {},
	SM_FullscreenButton: class extends self.ISpriteInstance {},
	SM_HomeButton: class extends self.ISpriteInstance {},
	SM_SoundButton: class extends self.ISpriteInstance {},
	SM_HomeButton2: class extends self.ISpriteInstance {},
	PopUpBG: class extends self.ISpriteInstance {},
	SplashBG: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	BrandImage: class extends self.ISpriteInstance {},
	boardPosition: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	winnerText: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	difficultyText: class extends self.ITextInstance {},
	SinglePlayer: class extends self.ISpriteInstance {},
	_2player: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	CloseSM: class extends self.ISpriteInstance {},
	WinnerBanner: class extends self.ISpriteInstance {},
	CnnectFour: class extends self.ISpriteInstance {},
	Restart2: class extends self.ISpriteInstance {},
	backGround: class extends self.ISpriteInstance {},
	piece: class extends self.ISpriteInstance {},
	errorText: class extends self.ITextInstance {},
	newGame: class extends self.ISpriteInstance {},
	Shop_Mask: class extends self.ISpriteInstance {},
	ShopDecals: class extends self.ISpriteInstance {},
	DecalsShopObject: class extends self.ISpriteInstance {},
	InShop_Btn: class extends self.ISpriteInstance {},
	Shop_Buy_txt: class extends self.ITextInstance {},
	ShopPieces: class extends self.ISpriteInstance {},
	PiecesShopObject: class extends self.ISpriteInstance {},
	ShopCollections: class extends self.ISpriteInstance {},
	CollectionsShopObject: class extends self.ISpriteInstance {},
	PiecesArray: class extends self.IArrayInstance {},
	DecalsArray: class extends self.IArrayInstance {},
	CollectionsArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Decal0: class extends self.ISpriteInstance {},
	Undo: class extends self.ISpriteInstance {},
	Skin0: class extends self.ISpriteInstance {},
	ModeSelectDifficulties: class extends self.ISpriteInstance {},
	Difiiculties: class extends self.ISpriteInstance {},
	DPin: class extends self.ISpriteInstance {},
	PlayB: class extends self.ISpriteInstance {},
	GameBGPC: class extends self.ISpriteInstance {},
	LogoBGLandscape: class extends self.ISpriteInstance {},
	LogoShineScreen: class extends self.ISpriteInstance {},
	LogoBG: class extends self.ISpriteInstance {},
	PiecesButton: class extends self.ISpriteInstance {},
	DecalButton: class extends self.ISpriteInstance {},
	CollectionsButton: class extends self.ISpriteInstance {},
	Shine: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	EquipmentButtonsParticleScreen: class extends self.ISpriteInstance {},
	SettingPopUp: class extends self.ISpriteInstance {},
	VibrateOn: class extends self.ISpriteInstance {},
	CloseSettings: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	HeadlineLandscape: class extends self.ISpriteInstance {},
	TimeModlandscape: class extends self.ISpriteInstance {},
	TimeButton: class extends self.ISpriteInstance {},
	CoinsLandscape: class extends self.ISpriteInstance {},
	InfoButtonladnscape: class extends self.ISpriteInstance {},
	Coins: class extends self.ITextInstance {},
	ExtraCoins_: class extends self.ISpriteInstance {},
	RadialBG: class extends self.ISpriteInstance {},
	Radial: class extends self.ISpriteInstance {},
	LeftHalf: class extends self.ISpriteInstance {},
	Radial2: class extends self.ISpriteInstance {},
	RightHalf: class extends self.ISpriteInstance {},
	ShopDecals8: class extends self.ISpriteInstance {},
	ShopDecals7: class extends self.ISpriteInstance {},
	ShopDecals6: class extends self.ISpriteInstance {},
	ShopDecals5: class extends self.ISpriteInstance {},
	ShopDecals4: class extends self.ISpriteInstance {},
	ShopDecals2: class extends self.ISpriteInstance {},
	ShopDecals1: class extends self.ISpriteInstance {},
	ShopDecals3: class extends self.ISpriteInstance {},
	ShopDecals0: class extends self.ISpriteInstance {},
	DecalPrice: class extends self.ISpriteInstance {},
	PriceTag: class extends self.ITextInstance {},
	TabsB: class extends self.ISpriteInstance {},
	CollectionsTeblandscape: class extends self.ISpriteInstance {},
	PiecesTablandscape: class extends self.ISpriteInstance {},
	DecalsTablandscape: class extends self.ISpriteInstance {},
	UsingFrameSmall: class extends self.ISpriteInstance {},
	BuyButtonLandscape: class extends self.ISpriteInstance {},
	ShopPieces8: class extends self.ISpriteInstance {},
	ShopPieces4: class extends self.ISpriteInstance {},
	ShopPieces5: class extends self.ISpriteInstance {},
	ShopPieces6: class extends self.ISpriteInstance {},
	ShopPieces7: class extends self.ISpriteInstance {},
	ShopPieces2: class extends self.ISpriteInstance {},
	ShopPieces3: class extends self.ISpriteInstance {},
	ShopPieces1: class extends self.ISpriteInstance {},
	ShopPieces0: class extends self.ISpriteInstance {},
	collectionsShop0: class extends self.ISpriteInstance {},
	collectionsShop2: class extends self.ISpriteInstance {},
	collectionsShop4: class extends self.ISpriteInstance {},
	collectionsShop1: class extends self.ISpriteInstance {},
	collectionsShop3: class extends self.ISpriteInstance {},
	CollectionPrice: class extends self.ISpriteInstance {},
	UsingFrameBig: class extends self.ISpriteInstance {},
	PiecesPC: class extends self.ISpriteInstance {},
	DecalsPC: class extends self.ISpriteInstance {},
	CollectionsPC: class extends self.ISpriteInstance {},
	CloseShopButton: class extends self.ISpriteInstance {},
	TimeModePopUp: class extends self.ISpriteInstance {},
	YesButtonlandscape: class extends self.ISpriteInstance {},
	NoButtonlandscape: class extends self.ISpriteInstance {},
	BoardPC: class extends self.ISpriteInstance {},
	ChosenPiece: class extends self.ISpriteInstance {},
	possibleMove: class extends self.ISpriteInstance {},
	PlayerHolder: class extends self.ISpriteInstance {},
	Skin1: class extends self.ISpriteInstance {},
	Skin2: class extends self.ISpriteInstance {},
	Skin3: class extends self.ISpriteInstance {},
	Skin4: class extends self.ISpriteInstance {},
	Skin5: class extends self.ISpriteInstance {},
	Skin6: class extends self.ISpriteInstance {},
	Skin7: class extends self.ISpriteInstance {},
	Skin8: class extends self.ISpriteInstance {},
	Decal1: class extends self.ISpriteInstance {},
	Decal2: class extends self.ISpriteInstance {},
	Decal3: class extends self.ISpriteInstance {},
	Decal4: class extends self.ISpriteInstance {},
	Decal5: class extends self.ISpriteInstance {},
	Decal6: class extends self.ISpriteInstance {},
	Decal7: class extends self.ISpriteInstance {},
	Decal8: class extends self.ISpriteInstance {},
	KeepPlayingPopUp: class extends self.ISpriteInstance {},
	KeepPlayingButtonlandscape: class extends self.ISpriteInstance {},
	LoseTextlandscape: class extends self.ISpriteInstance {},
	ResignButtonlandscape_: class extends self.ISpriteInstance {},
	EatenCount: class extends self.ITextInstance {},
	TimeDotsHolder: class extends self.ISpriteInstance {},
	Dotlandscape: class extends self.ISpriteInstance {},
	Avatar: class extends self.ISpriteInstance {},
	AvatarTimer: class extends self.ISpriteInstance {},
	Collection2: class extends self.ISpriteInstance {},
	Collection0: class extends self.ISpriteInstance {},
	Collection1: class extends self.ISpriteInstance {},
	Collection3: class extends self.ISpriteInstance {},
	Collection4: class extends self.ISpriteInstance {},
	hard: class extends self.ISpriteInstance {},
	med: class extends self.ISpriteInstance {},
	Diff: class extends self.ISpriteInstance {},
	CoinsWon: class extends self.ISpriteInstance {},
	PopUpShineScreenlandscape: class extends self.ISpriteInstance {},
	CoinsShineScreenlandscape: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	TopUIBar: class extends self.ISpriteInstance {},
	LogoBGHome: class extends self.ISpriteInstance {},
	PlayButtonsShine: class extends self.ISpriteInstance {},
	CollectionsMobile: class extends self.ISpriteInstance {},
	PiecesMobile: class extends self.ISpriteInstance {},
	DecalsMobile: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	GameBGMobile: class extends self.ISpriteInstance {},
	Vibration: class extends self.ISpriteInstance {},
	Rules: class extends self.ISpriteInstance {},
	CloseInfo: class extends self.ISpriteInstance {},
	Eatting_effect: class extends self.ISpriteInstance {},
	Eatting_effect2: class extends self.ISpriteInstance {},
	ScrollBG: class extends self.ISpriteInstance {},
	ScrollTab: class extends self.ISpriteInstance {},
	MyRuller: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	Asset6: class extends self.ISpriteInstance {},
	Asset7: class extends self.ISpriteInstance {},
	NoCoins: class extends self.ITextInstance {},
	NoMoves: class extends self.ITextInstance {},
	_30TurnsDraw: class extends self.ITextInstance {},
	chet: class extends self.ISpriteInstance {},
	PopUpShineScreenlandscape2: class extends self.ISpriteInstance {},
	Untitled: class extends self.ISpriteInstance {},
	Anchor: class extends self.ISpriteInstance {},
	test: class extends self.ISpriteInstance {},
	FXCoin: class extends self.ISpriteInstance {},
	CoinExplo: class extends self.IParticlesInstance {},
	DoubleCoinsButton: class extends self.ISpriteInstance {},
	ExtraTimeText: class extends self.ITextInstance {},
	PiecesRewardText: class extends self.ITextInstance {},
	KingsBonus: class extends self.ITextInstance {},
	AteKingsBonus: class extends self.ITextInstance {},
	KingTakesBonus: class extends self.ITextInstance {},
	DoublesBonus: class extends self.ITextInstance {},
	TripleBonus: class extends self.ITextInstance {},
	RewardAmount: class extends self.ITextInstance {},
	DefficultyBonusText: class extends self.ITextInstance {},
	TotalCoinsReward: class extends self.ITextInstance {},
	Coin: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	RewardsScreen: class extends self.ISpriteInstance {},
	TempArray: class extends self.IArrayInstance {},
	ButtonsSpawner: class extends self.ISpriteInstance {},
	Store: class extends self.ISpriteInstance {},
	Restart3: class extends self.ISpriteInstance {},
	RewardCoins: class extends self.ITextInstance {},
	StatsTitle: class extends self.ISpriteInstance {},
	StatsPanelLine: class extends self.ISpriteInstance {},
	StatsTitle2: class extends self.ISpriteInstance {},
	NotEnoughCoins: class extends self.ISpriteInstance {},
	NoWifi: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	Blackscreen_Rotate: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	Message: class extends self.ISpriteInstance {},
	GlobalButtons: class extends self.ISpriteInstance {},
	FullScreenButtons: class extends self.ISpriteInstance {},
	HomeButtons: class extends self.ISpriteInstance {},
	SoundButtons: class extends self.ISpriteInstance {},
	ModeSelectTweens: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	DecalsSkins: class extends self.ISpriteInstance {},
	PiecesSkins: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	DecalsShop: class extends self.ISpriteInstance {},
	PiecesShop: class extends self.ISpriteInstance {},
	CollectionsShop: class extends self.ISpriteInstance {},
	ShopSpawners: class extends self.ISpriteInstance {},
	ShopHolders: class extends self.ISpriteInstance {},
	ShopPageSelection: class extends self.ISpriteInstance {},
	CollectionSkins: class extends self.ISpriteInstance {},
	Difficulties: class extends self.ISpriteInstance {},
	VibrateButtons: class extends self.ISpriteInstance {},
	GameBGS: class extends self.ISpriteInstance {},
	RadialTeam: class extends self.ISpriteInstance {},
	CanTouch: class extends self.ISpriteInstance {},
	BouncyBois: class extends self.ISpriteInstance {},
	FadeTexts: class extends self.ITextInstance {}
}