const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Date,
		C3.Plugins.filechooser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Json,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.wrap,
		C3.Behaviors.custom,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.List,
		C3.Plugins.sliderbar,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.LOS,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Plugins.GameAnalytics,
		C3.Plugins.NinePatch,
		C3.Behaviors.Fade,
		C3.Plugins.PlaygamaBridge,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokencount,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.GameAnalytics.Acts.addDesignEvent,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Particles.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Behaviors.Platform.Exps.Speed,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Exps.Gravity,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.PlaygamaBridge.Acts.SendMessage,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.PlaygamaBridge.Cnds.OnRewardedOpened,
		C3.Plugins.PlaygamaBridge.Cnds.OnInterstitialOpened,
		C3.Plugins.PlaygamaBridge.Cnds.OnRewardedClosed,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.PlaygamaBridge.Acts.ShowInterstitial,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Date.Exps.GetDate,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.NinePatch.Cnds.HasTags,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.PlaygamaBridge.Acts.ShowRewarded,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Particles.Acts.FastForward,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.PlaygamaBridge.Cnds.OnRewardedRewarded,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.GameAnalytics.Acts.initialize,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.PlaygamaBridge.Cnds.IsMobile,
		C3.Plugins.PlaygamaBridge.Cnds.IsTablet,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.PlaygamaBridge.Acts.Rate,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Particles.Exps.Y,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Bullet.Exps.DistanceTravelled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Exps.Angle,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.Sprite.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{Date: 0},
	{FileChooser: 0},
	{LocalStorage: 0},
	{JSON: 0},
	{Dirt: 0},
	{Grass: 0},
	{id: 0},
	{Solid: 0},
	{Ground: 0},
	{ParticlesDust: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{tree: 0},
	{rock: 0},
	{ForestFront: 0},
	{Wrap: 0},
	{Custom: 0},
	{Cloud: 0},
	{FrontBG: 0},
	{TB_5: 0},
	{tb_nebo2: 0},
	{Anchor: 0},
	{TiledBackground3: 0},
	{up_dekor_lvl2: 0},
	{tb_nebo3: 0},
	{eHP0: 0},
	{maxhp: 0},
	{eHP1: 0},
	{eHP2: 0},
	{HP0: 0},
	{hp1: 0},
	{hp2: 0},
	{bMobileCtrl: 0},
	{hpBG: 0},
	{hpBG2: 0},
	{btnPAUSE: 0},
	{Tween: 0},
	{b_Ctrl_map: 0},
	{PlayBtn: 0},
	{point_map: 0},
	{type: 0},
	{cena_tip_pokupki: 0},
	{TextMenu: 0},
	{ad_used: 0},
	{Upgbtn: 0},
	{UpgLevelIcon: 0},
	{UpgradeIcon: 0},
	{MainMap: 0},
	{Monet: 0},
	{MonetBG: 0},
	{MainMenuBG: 0},
	{Indicator: 0},
	{RewardBtn: 0},
	{Pin: 0},
	{Text_bust_ammo: 0},
	{tutor_text: 0},
	{Text_dmg: 0},
	{Sine: 0},
	{ui_boss_text: 0},
	{LC_btn: 0},
	{LC_TankIcon: 0},
	{hp: 0},
	{shield: 0},
	{speed: 0},
	{dmg: 0},
	{reload: 0},
	{price: 0},
	{LC_TankSetup: 0},
	{input: 0},
	{LC_tSlider: 0},
	{LC_Input: 0},
	{tSelectLevel: 0},
	{List: 0},
	{List2: 0},
	{SliderBar: 0},
	{TextInput: 0},
	{DebugTank: 0},
	{tLevel: 0},
	{UiBG: 0},
	{shift_x: 0},
	{BTN: 0},
	{Settings: 0},
	{pDust: 0},
	{Tank_Body: 0},
	{MaxSpeed: 0},
	{Hill: 0},
	{unHill: 0},
	{Forward: 0},
	{bust_snaryd: 0},
	{bust_ammo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{LineOfSight: 0},
	{Timer: 0},
	{Tank_core: 0},
	{Tank_Head: 0},
	{GunAngle: 0},
	{UpAngle: 0},
	{DownAngle: 0},
	{Tank_Gun: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Tank_Armor: 0},
	{TankTrup: 0},
	{Bullet0: 0},
	{HP: 0},
	{ReloadTime: 0},
	{Damage: 0},
	{Shield: 0},
	{Price: 0},
	{frame_bullet: 0},
	{pzKpfw38: 0},
	{EnemyGUN: 0},
	{BulletEnemy: 0},
	{EnemyTrup: 0},
	{pzKpfwIV: 0},
	{pzKpfw38T: 0},
	{Boss1: 0},
	{tigr: 0},
	{sturmpanzerIV: 0},
	{panzerwerfer42: 0},
	{Boss2: 0},
	{Boss3: 0},
	{Boss4: 0},
	{Boss5: 0},
	{pzKpfwIV_2: 0},
	{pzKpfw38_2: 0},
	{panzerwerfer42_2: 0},
	{pzKpfw38T_2: 0},
	{tigr_2: 0},
	{sturmpanzerIV_2: 0},
	{Bullet_boss: 0},
	{Boss1_2: 0},
	{Boss2_2: 0},
	{Boss3_2: 0},
	{Boss4_2: 0},
	{Boss5_2: 0},
	{TankTriggerB0: 0},
	{TankTriggerF0: 0},
	{tip: 0},
	{stap: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{GameSave: 0},
	{tank_on_level: 0},
	{Levels: 0},
	{TanksData: 0},
	{DevSave: 0},
	{arr_EnemyPool: 0},
	{ParticlesChangeTank: 0},
	{eHit: 0},
	{eShot: 0},
	{eRikosh: 0},
	{eBoom: 0},
	{Rotate: 0},
	{traser: 0},
	{Bbalon: 0},
	{Bwheel: 0},
	{EBArrow: 0},
	{EBTable: 0},
	{BZaslon: 0},
	{EnergoBlock: 0},
	{Shlang: 0},
	{Shlang0: 0},
	{ang1: 0},
	{ang2: 0},
	{b2_str: 0},
	{Sine2: 0},
	{Bbody: 0},
	{Bgun0: 0},
	{isActive: 0},
	{Bgun1: 0},
	{bGunArt: 0},
	{EBBG: 0},
	{BulletEnemyArt: 0},
	{BossGroundCollider: 0},
	{ArtDetector: 0},
	{bDeadBoss: 0},
	{bBgfone: 0},
	{bFone: 0},
	{bGround: 0},
	{bHpGlass: 0},
	{bTree: 0},
	{Kolushka: 0},
	{Warning: 0},
	{brankahp: 0},
	{bfonhp: 0},
	{bhp: 0},
	{bDeadBoss2: 0},
	{AdsTimer: 0},
	{GameAnalytics: 0},
	{Discord: 0},
	{Text: 0},
	{LangChanger: 0},
	{fin_dekor: 0},
	{nomer: 0},
	{ui_star: 0},
	{ui_lu4: 0},
	{part_fin_star: 0},
	{confetti: 0},
	{part_conf: 0},
	{ui_upp_marker: 0},
	{dekor_ui: 0},
	{ui_radar: 0},
	{ui_radar_hero: 0},
	{uid_enemy: 0},
	{ui_rad_enemy: 0},
	{b2korpus: 0},
	{b2guss: 0},
	{nom: 0},
	{hitpoint: 0},
	{b2batarey: 0},
	{point_fire: 0},
	{b2lazer: 0},
	{bullet_speedd: 0},
	{b2puha: 0},
	{b2_tb_nebo: 0},
	{b2_tb_zad: 0},
	{b2_tb_lay3: 0},
	{b2_road: 0},
	{b2_dekor: 0},
	{b2_tb_trava: 0},
	{lazer_stap: 0},
	{batarey_nom: 0},
	{boss_stap: 0},
	{minom_shift: 0},
	{bomb_count: 0},
	{dron_goo: 0},
	{boss_data: 0},
	{tb_laser: 0},
	{part_laser_target: 0},
	{part_spark_bat: 0},
	{part_laser_hit: 0},
	{b3_roket: 0},
	{part_roket: 0},
	{part_spark_bat2: 0},
	{b2_luk: 0},
	{tag: 0},
	{max_point: 0},
	{max_width: 0},
	{ui_info_tank_bar: 0},
	{sc: 0},
	{butt: 0},
	{ui_but_buster: 0},
	{ui_pod_upgred: 0},
	{ui_ikon_m: 0},
	{smoke: 0},
	{pod_step: 0},
	{world_nom: 0},
	{level_go: 0},
	{start_lvl_money: 0},
	{coin_ad: 0},
	{ad_type: 0},
	{gem_on_tank: 0},
	{ui_gem_badge: 0},
	{reward_coin: 0},
	{reward_gem: 0},
	{pokupka_yan: 0},
	{show_rating: 0},
	{inter_ad_del: 0},
	{pause_ad: 0},
	{a_data: 0},
	{part_upgreyd: 0},
	{ui_9p_gift: 0},
	{money: 0},
	{gem: 0},
	{b_avia: 0},
	{b_remont: 0},
	{b_ammo: 0},
	{ui_gift_unit: 0},
	{tb_beck_gift: 0},
	{ui_butt_gift: 0},
	{ui_store_un: 0},
	{teg: 0},
	{ui_store_buttn: 0},
	{onn: 0},
	{ui_bust_game: 0},
	{aktiv: 0},
	{samolet: 0},
	{sam_remka: 0},
	{part_remka: 0},
	{avia_bomb: 0},
	{sam_ammo: 0},
	{ammo_icon: 0},
	{tb_start_level: 0},
	{part_sled_g: 0},
	{part_sled_en: 0},
	{damage: 0},
	{dop_enemy: 0},
	{dop_en_puha: 0},
	{dop_ded: 0},
	{part_bomb_dim: 0},
	{part_bomb_w: 0},
	{part_bomb_w2: 0},
	{part_ddimm: 0},
	{Fade: 0},
	{boom_kusok: 0},
	{part_kusok_dim: 0},
	{TiledBackground6: 0},
	{tb_zeml_m1: 0},
	{tb_m2_updek: 0},
	{tb_neboscr_m2: 0},
	{tb_w4_shill1: 0},
	{tb_black: 0},
	{tb_upp_m1: 0},
	{b3_tb_zad: 0},
	{start_xx: 0},
	{bBoss_05: 0},
	{most: 0},
	{b05_bash: 0},
	{time_fire: 0},
	{b05_stvol: 0},
	{b05_gusli: 0},
	{b05_minom: 0},
	{target: 0},
	{bbboss4: 0},
	{bbboss_armor: 0},
	{dron_b: 0},
	{part_ddim_b4: 0},
	{samolet_vint: 0},
	{part_gun_tank: 0},
	{arr_tutorr: 0},
	{tutor_st: 0},
	{tutor_fon: 0},
	{tutor_trigger: 0},
	{ui_dekor: 0},
	{tutor_ava: 0},
	{ui_gam_b: 0},
	{ui_checkbox: 0},
	{ui_star_rating: 0},
	{ui_circle: 0},
	{ui_boss_podl: 0},
	{ui_lidboard: 0},
	{text_ui_dp: 0},
	{ui_lll: 0},
	{tb_zzz: 0},
	{tb_skyscraper: 0},
	{tb_blck_lay0: 0},
	{tb_ruins: 0},
	{tb_bg_front: 0},
	{tb_boss0_redt: 0},
	{PlaygamaBridge: 0},
	{TankTriggers: 0},
	{CloseDistance: 0},
	{EnemyTank: 0},
	{GUI: 0},
	{myTank: 0},
	{EffectsDestroy: 0},
	{CurLevel: 0},
	{TankCreated: 0},
	{StartGame: 0},
	{EnemyCreated: 0},
	{tank_type: 0},
	{first_win_bonus: 0},
	{xx: 0},
	{yy: 0},
	{kuski: 0},
	{tutor: 0},
	{gift_nomer: 0},
	{gift_time: 0},
	{lang_data: 0},
	{Lang: 0},
	{platform: 0},
	{avtoriz: 0},
	{SaveSlot: 0},
	{Tank: 0},
	{OpenLevel: 0},
	{Gem: 0},
	{Money: 0},
	{Speed: 0},
	{Range: 0},
	{level_mod: 0},
	{lvl_Armor: 0},
	{lvl_pod_Armor: 0},
	{lvl_Gun: 0},
	{lvl_pod_Gun: 0},
	{lvl_Speed: 0},
	{lvl_pod_Speed: 0},
	{Purchased: 0},
	{ArmorPrice: 0},
	{GunPrice: 0},
	{SpeedPrice: 0},
	{Levelprice: 0},
	{Upgr_Stap: 0},
	{UpgradeBoostPrice: 0},
	{Xspeed: 0},
	{bust_avia: 0},
	{bust_remont: 0},
	{gun_stap: 0},
	{eHP: 0},
	{eShield: 0},
	{eSpeed: 0},
	{eDmg: 0},
	{eReload: 0},
	{ePrice: 0},
	{TokenatENEMY: 0},
	{gHP: 0},
	{gShield: 0},
	{tankID: 0},
	{tanksDistance: 0},
	{AudioVolume: 0},
	{LC_ActiveLevel: 0},
	{tankL: 0},
	{tankR: 0},
	{mapOpen: 0},
	{map_visible: 0},
	{SkipTutor: 0},
	{start_y: 0},
	{start_x: 0},
	{Index: 0},
	{upgr_onn: 0},
	{type_upgr: 0},
	{ad_up: 0},
	{fun_world_open: 0},
	{nom_gift: 0},
	{GameStage: 0},
	{stars: 0},
	{win_star_on: 0},
	{star_r: 0},
	{Level: 0},
	{levelNum: 0},
	{type_tank: 0},
	{BOSSHP0: 0},
	{BOSSHP1: 0},
	{BOSSHP2: 0},
	{gunID: 0},
	{count: 0},
	{hit: 0},
	{info_hp: 0},
	{crit: 0},
	{step: 0},
	{dop_parameter: 0},
	{time_scale: 0},
	{shot: 0},
	{bullet_id: 0},
	{vzriv: 0},
	{deystvie: 0},
	{id_boomb: 0},
	{angle_arrow: 0},
	{lay: 0},
	{size_x: 0},
	{size_y: 0},
	{text: 0},
	{font_size: 0},
	{ava_frame: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	FileChooser: class extends self.IWorldInstance {},
	LocalStorage: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Dirt: class extends self.ISpriteInstance {},
	Grass: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	ParticlesDust: class extends self.IParticlesInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	tree: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	ForestFront: class extends self.ISpriteInstance {},
	Cloud: class extends self.ISpriteInstance {},
	FrontBG: class extends self.ISpriteInstance {},
	TB_5: class extends self.ITiledBackgroundInstance {},
	tb_nebo2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	up_dekor_lvl2: class extends self.ISpriteInstance {},
	tb_nebo3: class extends self.ITiledBackgroundInstance {},
	eHP0: class extends self.ISpriteInstance {},
	eHP1: class extends self.ISpriteInstance {},
	eHP2: class extends self.ISpriteInstance {},
	HP0: class extends self.ISpriteInstance {},
	hp1: class extends self.ISpriteInstance {},
	hp2: class extends self.ISpriteInstance {},
	bMobileCtrl: class extends self.ISpriteInstance {},
	hpBG: class extends self.ISpriteInstance {},
	hpBG2: class extends self.ISpriteInstance {},
	btnPAUSE: class extends self.ISpriteInstance {},
	b_Ctrl_map: class extends self.ISpriteInstance {},
	PlayBtn: class extends self.ISpriteInstance {},
	point_map: class extends self.ISpriteInstance {},
	TextMenu: class extends self.ITextInstance {},
	Upgbtn: class extends self.ISpriteInstance {},
	UpgLevelIcon: class extends self.ISpriteInstance {},
	UpgradeIcon: class extends self.ISpriteInstance {},
	MainMap: class extends self.ISpriteInstance {},
	Monet: class extends self.ISpriteInstance {},
	MonetBG: class extends self.ISpriteInstance {},
	MainMenuBG: class extends self.ISpriteInstance {},
	Indicator: class extends self.ISpriteInstance {},
	RewardBtn: class extends self.ISpriteInstance {},
	Text_bust_ammo: class extends self.ITextInstance {},
	tutor_text: class extends self.ITextInstance {},
	Text_dmg: class extends self.ITextInstance {},
	ui_boss_text: class extends self.ITextInstance {},
	LC_btn: class extends self.IButtonInstance {},
	LC_TankIcon: class extends self.ISpriteInstance {},
	LC_TankSetup: class extends self.ISpriteInstance {},
	LC_tSlider: class extends self.ITextInstance {},
	LC_Input: class extends self.ITextInputInstance {},
	tSelectLevel: class extends self.ITextInstance {},
	List: class extends self.IListInstance {},
	List2: class extends self.IListInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	TextInput: class extends self.ITextInputInstance {},
	DebugTank: class extends self.ITextInstance {},
	tLevel: class extends self.ITextInstance {},
	UiBG: class extends self.ISpriteInstance {},
	BTN: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	pDust: class extends self.IParticlesInstance {},
	Tank_Body: class extends self.ISpriteInstance {},
	Tank_core: class extends self.ISpriteInstance {},
	Tank_Head: class extends self.ISpriteInstance {},
	Tank_Gun: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Tank_Armor: class extends self.ISpriteInstance {},
	TankTrup: class extends self.ISpriteInstance {},
	Bullet0: class extends self.ISpriteInstance {},
	pzKpfw38: class extends self.ISpriteInstance {},
	EnemyGUN: class extends self.ISpriteInstance {},
	BulletEnemy: class extends self.ISpriteInstance {},
	EnemyTrup: class extends self.ISpriteInstance {},
	pzKpfwIV: class extends self.ISpriteInstance {},
	pzKpfw38T: class extends self.ISpriteInstance {},
	Boss1: class extends self.ISpriteInstance {},
	tigr: class extends self.ISpriteInstance {},
	sturmpanzerIV: class extends self.ISpriteInstance {},
	panzerwerfer42: class extends self.ISpriteInstance {},
	Boss2: class extends self.ISpriteInstance {},
	Boss3: class extends self.ISpriteInstance {},
	Boss4: class extends self.ISpriteInstance {},
	Boss5: class extends self.ISpriteInstance {},
	pzKpfwIV_2: class extends self.ISpriteInstance {},
	pzKpfw38_2: class extends self.ISpriteInstance {},
	panzerwerfer42_2: class extends self.ISpriteInstance {},
	pzKpfw38T_2: class extends self.ISpriteInstance {},
	tigr_2: class extends self.ISpriteInstance {},
	sturmpanzerIV_2: class extends self.ISpriteInstance {},
	Bullet_boss: class extends self.ISpriteInstance {},
	Boss1_2: class extends self.ISpriteInstance {},
	Boss2_2: class extends self.ISpriteInstance {},
	Boss3_2: class extends self.ISpriteInstance {},
	Boss4_2: class extends self.ISpriteInstance {},
	Boss5_2: class extends self.ISpriteInstance {},
	TankTriggerB0: class extends self.ISpriteInstance {},
	TankTriggerF0: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	GameSave: class extends self.IArrayInstance {},
	Levels: class extends self.IArrayInstance {},
	TanksData: class extends self.IArrayInstance {},
	DevSave: class extends self.IArrayInstance {},
	arr_EnemyPool: class extends self.IArrayInstance {},
	ParticlesChangeTank: class extends self.IParticlesInstance {},
	eHit: class extends self.ISpriteInstance {},
	eShot: class extends self.ISpriteInstance {},
	eRikosh: class extends self.ISpriteInstance {},
	eBoom: class extends self.ISpriteInstance {},
	traser: class extends self.ISpriteInstance {},
	Bbalon: class extends self.ISpriteInstance {},
	Bwheel: class extends self.ISpriteInstance {},
	EBArrow: class extends self.ISpriteInstance {},
	EBTable: class extends self.ISpriteInstance {},
	BZaslon: class extends self.ISpriteInstance {},
	EnergoBlock: class extends self.ISpriteInstance {},
	Shlang: class extends self.ISpriteInstance {},
	Shlang0: class extends self.ISpriteInstance {},
	b2_str: class extends self.ISpriteInstance {},
	Bbody: class extends self.ISpriteInstance {},
	Bgun0: class extends self.ISpriteInstance {},
	Bgun1: class extends self.ISpriteInstance {},
	bGunArt: class extends self.ISpriteInstance {},
	EBBG: class extends self.ISpriteInstance {},
	BulletEnemyArt: class extends self.ISpriteInstance {},
	BossGroundCollider: class extends self.ISpriteInstance {},
	ArtDetector: class extends self.ISpriteInstance {},
	bDeadBoss: class extends self.ISpriteInstance {},
	bBgfone: class extends self.ISpriteInstance {},
	bFone: class extends self.ISpriteInstance {},
	bGround: class extends self.ISpriteInstance {},
	bHpGlass: class extends self.ISpriteInstance {},
	bTree: class extends self.ISpriteInstance {},
	Kolushka: class extends self.ISpriteInstance {},
	Warning: class extends self.ISpriteInstance {},
	brankahp: class extends self.ISpriteInstance {},
	bfonhp: class extends self.ISpriteInstance {},
	bhp: class extends self.ISpriteInstance {},
	bDeadBoss2: class extends self.ISpriteInstance {},
	AdsTimer: class extends self.ISpriteInstance {},
	GameAnalytics: class extends self.IInstance {},
	reload: class extends self.ISpriteInstance {},
	Discord: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	LangChanger: class extends self.ISpriteInstance {},
	fin_dekor: class extends self.ISpriteInstance {},
	ui_star: class extends self.ISpriteInstance {},
	ui_lu4: class extends self.ISpriteInstance {},
	part_fin_star: class extends self.IParticlesInstance {},
	confetti: class extends self.ISpriteInstance {},
	part_conf: class extends self.IParticlesInstance {},
	ui_upp_marker: class extends self.ISpriteInstance {},
	dekor_ui: class extends self.ISpriteInstance {},
	ui_radar: class extends self.ISpriteInstance {},
	ui_radar_hero: class extends self.ISpriteInstance {},
	ui_rad_enemy: class extends self.ISpriteInstance {},
	b2korpus: class extends self.ISpriteInstance {},
	b2guss: class extends self.ITiledBackgroundInstance {},
	b2batarey: class extends self.ISpriteInstance {},
	b2lazer: class extends self.ISpriteInstance {},
	b2puha: class extends self.ISpriteInstance {},
	b2_tb_nebo: class extends self.ITiledBackgroundInstance {},
	b2_tb_zad: class extends self.ITiledBackgroundInstance {},
	b2_tb_lay3: class extends self.ITiledBackgroundInstance {},
	b2_road: class extends self.ISpriteInstance {},
	b2_dekor: class extends self.ISpriteInstance {},
	b2_tb_trava: class extends self.ITiledBackgroundInstance {},
	boss_data: class extends self.ISpriteInstance {},
	tb_laser: class extends self.ITiledBackgroundInstance {},
	part_laser_target: class extends self.IParticlesInstance {},
	part_spark_bat: class extends self.IParticlesInstance {},
	part_laser_hit: class extends self.IParticlesInstance {},
	b3_roket: class extends self.ISpriteInstance {},
	part_roket: class extends self.IParticlesInstance {},
	part_spark_bat2: class extends self.IParticlesInstance {},
	b2_luk: class extends self.ISpriteInstance {},
	ui_info_tank_bar: class extends self.ITiledBackgroundInstance {},
	ui_but_buster: class extends self.ISpriteInstance {},
	ui_pod_upgred: class extends self.ISpriteInstance {},
	ui_ikon_m: class extends self.ISpriteInstance {},
	a_data: class extends self.ISpriteInstance {},
	part_upgreyd: class extends self.IParticlesInstance {},
	ui_9p_gift: class extends self.IWorldInstance {},
	ui_gift_unit: class extends self.ISpriteInstance {},
	tb_beck_gift: class extends self.ITiledBackgroundInstance {},
	ui_butt_gift: class extends self.ISpriteInstance {},
	ui_store_un: class extends self.ISpriteInstance {},
	ui_store_buttn: class extends self.ISpriteInstance {},
	ui_bust_game: class extends self.ISpriteInstance {},
	samolet: class extends self.ISpriteInstance {},
	sam_remka: class extends self.ISpriteInstance {},
	part_remka: class extends self.IParticlesInstance {},
	avia_bomb: class extends self.ISpriteInstance {},
	sam_ammo: class extends self.ISpriteInstance {},
	ammo_icon: class extends self.ISpriteInstance {},
	tb_start_level: class extends self.ITiledBackgroundInstance {},
	part_sled_g: class extends self.IParticlesInstance {},
	part_sled_en: class extends self.IParticlesInstance {},
	dop_enemy: class extends self.ISpriteInstance {},
	dop_en_puha: class extends self.ISpriteInstance {},
	dop_ded: class extends self.ISpriteInstance {},
	part_bomb_dim: class extends self.IParticlesInstance {},
	part_bomb_w: class extends self.IParticlesInstance {},
	part_bomb_w2: class extends self.IParticlesInstance {},
	part_ddimm: class extends self.IParticlesInstance {},
	boom_kusok: class extends self.ISpriteInstance {},
	part_kusok_dim: class extends self.IParticlesInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	tb_zeml_m1: class extends self.ITiledBackgroundInstance {},
	tb_m2_updek: class extends self.ITiledBackgroundInstance {},
	tb_neboscr_m2: class extends self.ITiledBackgroundInstance {},
	tb_w4_shill1: class extends self.ITiledBackgroundInstance {},
	tb_black: class extends self.ITiledBackgroundInstance {},
	tb_upp_m1: class extends self.ITiledBackgroundInstance {},
	b3_tb_zad: class extends self.ITiledBackgroundInstance {},
	bBoss_05: class extends self.ISpriteInstance {},
	most: class extends self.ISpriteInstance {},
	b05_bash: class extends self.ISpriteInstance {},
	b05_stvol: class extends self.ISpriteInstance {},
	b05_gusli: class extends self.ISpriteInstance {},
	b05_minom: class extends self.ISpriteInstance {},
	target: class extends self.ISpriteInstance {},
	bbboss4: class extends self.ISpriteInstance {},
	bbboss_armor: class extends self.ISpriteInstance {},
	dron_b: class extends self.ISpriteInstance {},
	part_ddim_b4: class extends self.IParticlesInstance {},
	samolet_vint: class extends self.ISpriteInstance {},
	part_gun_tank: class extends self.IParticlesInstance {},
	arr_tutorr: class extends self.IArrayInstance {},
	tutor_st: class extends self.ISpriteInstance {},
	tutor_fon: class extends self.IWorldInstance {},
	tutor_trigger: class extends self.ISpriteInstance {},
	ui_dekor: class extends self.ISpriteInstance {},
	tutor_ava: class extends self.ISpriteInstance {},
	ui_gam_b: class extends self.ISpriteInstance {},
	ui_checkbox: class extends self.ISpriteInstance {},
	ui_star_rating: class extends self.ISpriteInstance {},
	ui_circle: class extends self.ISpriteInstance {},
	ui_boss_podl: class extends self.ISpriteInstance {},
	ui_lidboard: class extends self.ISpriteInstance {},
	text_ui_dp: class extends self.ITextInstance {},
	ui_lll: class extends self.ISpriteInstance {},
	tb_zzz: class extends self.ITiledBackgroundInstance {},
	tb_skyscraper: class extends self.ITiledBackgroundInstance {},
	tb_blck_lay0: class extends self.ITiledBackgroundInstance {},
	tb_ruins: class extends self.ITiledBackgroundInstance {},
	tb_bg_front: class extends self.ITiledBackgroundInstance {},
	tb_boss0_redt: class extends self.ITiledBackgroundInstance {},
	PlaygamaBridge: class extends self.IInstance {},
	TankTriggers: class extends self.ISpriteInstance {},
	EnemyTank: class extends self.ISpriteInstance {},
	GUI: class extends self.ISpriteInstance {},
	myTank: class extends self.ISpriteInstance {},
	EffectsDestroy: class extends self.ISpriteInstance {}
}