/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
 screenfull
 v5.0.0 - 2019-09-09
 (c) Sindre Sorhus; MIT License
*/
(function(){function a(d){d=String(d);return d.charAt(0).toUpperCase()+d.slice(1)}function f(d,w){var z=-1,v=d?d.length:0;if("number"==typeof v&&-1<v&&v<=x)for(;++z<v;)w(d[z],z,d);else g(d,w)}function b(d){d=String(d).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(d)?d:a(d)}function g(d,w){for(var z in d)u.call(d,z)&&w(d[z],z,d)}function r(d){return null==d?a(d):E.call(d).slice(8,-1)}function m(d,w){var z=null!=d?typeof d[w]:"number";return!/^(?:boolean|number|string|undefined)$/.test(z)&&
("object"==z?!!d[w]:!0)}function h(d){return String(d).replace(/([ -])(?!$)/g,"$1?")}function c(d,w){var z=null;f(d,function(v,y){z=w(z,v,y,d)});return z}function l(d){function w(M){return c(M,function(K,I){var N=I.pattern||h(I);!K&&(K=RegExp("\\b"+N+" *\\d+[.\\w_]*","i").exec(d)||RegExp("\\b"+N+" *\\w+-[\\w]*","i").exec(d)||RegExp("\\b"+N+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(d))&&((K=String(I.label&&!RegExp(N,"i").test(I.label)?I.label:K).split("/"))[1]&&!/[\d.]+/.test(K[0])&&(K[0]+=
" "+K[1]),I=I.label||I,K=b(K[0].replace(RegExp(N,"i"),I).replace(RegExp("; *(?:"+I+"[_-])?","i")," ").replace(RegExp("("+I+")[-_.]?(\\w)","i"),"$1 $2")));return K})}function z(M){return c(M,function(K,I){return K||(RegExp(I+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(d)||0)[1]||null})}var v=n,y=d&&"object"==typeof d&&"String"!=r(d);y&&(v=d,d=null);var F=v.navigator||{},p=F.userAgent||"";d||(d=p);var L=y?!!F.likeChrome:/\bChrome\b/.test(d)&&!/internal|\n/i.test(E.toString()),
U=y?"Object":"ScriptBridgingProxyObject",W=y?"Object":"Environment",Q=y&&v.java?"JavaPackage":r(v.java),Y=y?"Object":"RuntimeObject";W=(Q=/\bJava/.test(Q)&&v.java)&&r(v.environment)==W;var R=Q?"a":"\u03b1",X=Q?"b":"\u03b2",S=v.document||{},P=v.operamini||v.opera,D=t.test(D=y&&P?P["[[Class]]"]:r(P))?D:P=null,e,Z=d;y=[];var aa=null,V=d==p;p=V&&P&&"function"==typeof P.version&&P.version();var G=function(M){return c(M,function(K,I){return K||RegExp("\\b"+(I.pattern||h(I))+"\\b","i").exec(d)&&(I.label||
I)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),A=function(M){return c(M,function(K,I){return K||RegExp("\\b"+(I.pattern||h(I))+"\\b","i").exec(d)&&(I.label||I)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),H=w([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),O=function(M){return c(M,function(K,I,N){return K||(I[H]||I[/^[a-z]+(?: +[a-z]+\b)*/i.exec(H)]||RegExp("\\b"+h(N)+"(?:\\b|\\w*\\d)","i").exec(d))&&N})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),B=function(M){return c(M,function(K,I){var N=I.pattern||h(I);if(!K&&(K=RegExp("\\b"+N+"(?:/[\\d.]+|[ \\w.]*)","i").exec(d))){var T=K,ba=I.label||I,ca={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};N&&ba&&/^Win/i.test(T)&&!/^Windows Phone /i.test(T)&&(ca=ca[/[\d.]+$/.exec(T)])&&(T="Windows "+ca);T=String(T);N&&ba&&(T=T.replace(RegExp(N,"i"),ba));K=T=b(T.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return K})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);G&&(G=[G]);O&&!H&&(H=w([O]));if(e=/\bGoogle TV\b/.exec(H))H=e[0];/\bSimulator\b/i.test(d)&&(H=(H?H+" ":"")+"Simulator");"Opera Mini"==A&&/\bOPiOS\b/.test(d)&&y.push("running in Turbo/Uncompressed mode");"IE"==A&&/\blike iPhone OS\b/.test(d)?(e=l(d.replace(/like iPhone OS/,"")),O=e.manufacturer,H=e.product):/^iP/.test(H)?(A||(A="Safari"),B="iOS"+((e=/ OS ([\d_]+)/i.exec(d))?" "+e[1].replace(/_/g,"."):"")):"Konqueror"!=A||/buntu/i.test(B)?O&&"Google"!=O&&
(/Chrome/.test(A)&&!/\bMobile Safari\b/i.test(d)||/\bVita\b/.test(H))||/\bAndroid\b/.test(B)&&/^Chrome/.test(A)&&/\bVersion\//i.test(d)?(A="Android Browser",B=/\bAndroid\b/.test(B)?B:"Android"):"Silk"==A?(/\bMobi/i.test(d)||(B="Android",y.unshift("desktop mode")),/Accelerated *= *true/i.test(d)&&y.unshift("accelerated")):"PaleMoon"==A&&(e=/\bFirefox\/([\d.]+)\b/.exec(d))?y.push("identifying as Firefox "+e[1]):"Firefox"==A&&(e=/\b(Mobile|Tablet|TV)\b/i.exec(d))?(B||(B="Firefox OS"),H||(H=e[1])):!A||
(e=!/\bMinefield\b/i.test(d)&&/\b(?:Firefox|Safari)\b/.exec(A))?(A&&!H&&/[\/,]|^[^(]+?\)/.test(d.slice(d.indexOf(e+"/")+8))&&(A=null),(e=H||O||B)&&(H||O||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(B))&&(A=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(B)?B:e)+" Browser")):"Electron"==A&&(e=(/\bChrome\/([\d.]+)\b/.exec(d)||0)[1])&&y.push("Chromium "+e):B="Kubuntu";p||(p=z(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",h(A),
"(?:Firefox|Minefield|NetFront)"]));if(e="iCab"==G&&3<parseFloat(p)&&"WebKit"||/\bOpera\b/.test(A)&&(/\bOPR\b/.test(d)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(d)&&!/^(?:Trident|EdgeHTML)$/.test(G)&&"WebKit"||!G&&/\bMSIE\b/i.test(d)&&("Mac OS"==B?"Tasman":"Trident")||"WebKit"==G&&/\bPlayStation\b(?! Vita\b)/i.test(A)&&"NetFront")G=[e];"IE"==A&&(e=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(d)||0)[1])?(A+=" Mobile",B="Windows Phone "+(/\+$/.test(e)?e:e+".x"),y.unshift("desktop mode")):/\bWPDesktop\b/i.test(d)?
(A="IE Mobile",B="Windows Phone 8.x",y.unshift("desktop mode"),p||(p=(/\brv:([\d.]+)/.exec(d)||0)[1])):"IE"!=A&&"Trident"==G&&(e=/\brv:([\d.]+)/.exec(d))&&(A&&y.push("identifying as "+A+(p?" "+p:"")),A="IE",p=e[1]);if(V){if(m(v,"global"))if(Q&&(e=Q.lang.System,Z=e.getProperty("os.arch"),B=B||e.getProperty("os.name")+" "+e.getProperty("os.version")),W){try{p=v.require("ringo/engine").version.join("."),A="RingoJS"}catch(M){(e=v.system)&&e.global.system==v.system&&(A="Narwhal",B||(B=e[0].os||null))}A||
(A="Rhino")}else"object"==typeof v.process&&!v.process.browser&&(e=v.process)&&("object"==typeof e.versions&&("string"==typeof e.versions.electron?(y.push("Node "+e.versions.node),A="Electron",p=e.versions.electron):"string"==typeof e.versions.nw&&(y.push("Chromium "+p,"Node "+e.versions.node),A="NW.js",p=e.versions.nw)),A||(A="Node.js",Z=e.arch,B=e.platform,p=(p=/[\d.]+/.exec(e.version))?p[0]:null));else r(e=v.runtime)==U?(A="Adobe AIR",B=e.flash.system.Capabilities.os):r(e=v.phantom)==Y?(A="PhantomJS",
p=(e=e.version||null)&&e.major+"."+e.minor+"."+e.patch):"number"==typeof S.documentMode&&(e=/\bTrident\/(\d+)/i.exec(d))?(p=[p,S.documentMode],(e=+e[1]+4)!=p[1]&&(y.push("IE "+p[1]+" mode"),G&&(G[1]=""),p[1]=e),p="IE"==A?String(p[1].toFixed(1)):p[0]):"number"==typeof S.documentMode&&/^(?:Chrome|Firefox)\b/.test(A)&&(y.push("masking as "+A+" "+p),A="IE",p="11.0",G=["Trident"],B="Windows");B=B&&b(B)}p&&(e=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(p)||/(?:alpha|beta)(?: ?\d)?/i.exec(d+";"+(V&&F.appMinorVersion))||
/\bMinefield\b/i.test(d)&&"a")&&(aa=/b/i.test(e)?"beta":"alpha",p=p.replace(RegExp(e+"\\+?$"),"")+("beta"==aa?X:R)+(/\d+\+?/.exec(e)||""));if("Fennec"==A||"Firefox"==A&&/\b(?:Android|Firefox OS)\b/.test(B))A="Firefox Mobile";else if("Maxthon"==A&&p)p=p.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(H))"Xbox 360"==H&&(B=null),"Xbox 360"==H&&/\bIEMobile\b/.test(d)&&y.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(A)&&(!A||H||/Browser|Mobi/.test(A))||"Windows CE"!=B&&!/Mobi/i.test(d))if("IE"==
A&&V)try{null===v.external&&y.unshift("platform preview")}catch(M){y.unshift("embedded")}else(/\bBlackBerry\b/.test(H)||/\bBB10\b/.test(d))&&(e=(RegExp(H.replace(/ +/g," *")+"/([.\\d]+)","i").exec(d)||0)[1]||p)?(e=[e,/BB10/.test(d)],B=(e[1]?(H=null,O="BlackBerry"):"Device Software")+" "+e[0],p=null):this!=g&&"Wii"!=H&&(V&&P||/Opera/.test(A)&&/\b(?:MSIE|Firefox)\b/i.test(d)||"Firefox"==A&&/\bOS X (?:\d+\.){2,}/.test(B)||"IE"==A&&(B&&!/^Win/.test(B)&&5.5<p||/\bWindows XP\b/.test(B)&&8<p||8==p&&!/\bTrident\b/.test(d)))&&
!t.test(e=l.call(g,d.replace(t,"")+";"))&&e.name&&(e="ing as "+e.name+((e=e.version)?" "+e:""),t.test(A)?(/\bIE\b/.test(e)&&"Mac OS"==B&&(B=null),e="identify"+e):(e="mask"+e,A=D?b(D.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(e)&&(B=null),V||(p=null)),G=["Presto"],y.push(e));else A+=" Mobile";if(e=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(d)||0)[1]){e=[parseFloat(e.replace(/\.(\d)$/,".0$1")),e];if("Safari"==A&&"+"==e[1].slice(-1))A="WebKit Nightly",aa="alpha",p=e[1].slice(0,-1);else if(p==
e[1]||p==(e[2]=(/\bSafari\/([\d.]+\+?)/i.exec(d)||0)[1]))p=null;e[1]=(/\bChrome\/([\d.]+)/i.exec(d)||0)[1];537.36==e[0]&&537.36==e[2]&&28<=parseFloat(e[1])&&"WebKit"==G&&(G=["Blink"]);V&&(L||e[1])?(G&&(G[1]="like Chrome"),e=e[1]||(e=e[0],530>e?1:532>e?2:532.05>e?3:533>e?4:534.03>e?5:534.07>e?6:534.1>e?7:534.13>e?8:534.16>e?9:534.24>e?10:534.3>e?11:535.01>e?12:535.02>e?"13+":535.07>e?15:535.11>e?16:535.19>e?17:536.05>e?18:536.1>e?19:537.01>e?20:537.11>e?"21+":537.13>e?23:537.18>e?24:537.24>e?25:537.36>
e?26:"Blink"!=G?"27":"28")):(G&&(G[1]="like Safari"),e=(e=e[0],400>e?1:500>e?2:526>e?3:533>e?4:534>e?"4+":535>e?5:537>e?6:538>e?7:601>e?8:"8"));G&&(G[1]+=" "+(e+="number"==typeof e?".x":/[.+]/.test(e)?"":"+"));"Safari"==A&&(!p||45<parseInt(p))&&(p=e)}"Opera"==A&&(e=/\bzbov|zvav$/.exec(B))?(A+=" ",y.unshift("desktop mode"),"zvav"==e?(A+="Mini",p=null):A+="Mobile",B=B.replace(RegExp(" *"+e+"$"),"")):"Safari"==A&&/\bChrome\b/.exec(G&&G[1])&&(y.unshift("desktop mode"),A="Chrome Mobile",p=null,/\bOS X\b/.test(B)?
(O="Apple",B="iOS 4.3+"):B=null);p&&0==p.indexOf(e=/[\d.]+$/.exec(B))&&-1<d.indexOf("/"+e+"-")&&(B=String(B.replace(e,"")).replace(/^ +| +$/g,""));G&&!/\b(?:Avant|Nook)\b/.test(A)&&(/Browser|Lunascape|Maxthon/.test(A)||"Safari"!=A&&/^iOS/.test(B)&&/\bSafari\b/.test(G[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(A)&&G[1])&&(e=G[G.length-1])&&y.push(e);y.length&&(y=["("+y.join("; ")+")"]);O&&H&&0>H.indexOf(O)&&y.push("on "+O);H&&y.push((/^on /.test(y[y.length-
1])?"":"on ")+H);if(B){var da=(e=/ ([\d.+]+)$/.exec(B))&&"/"==B.charAt(B.length-e[0].length-1);B={architecture:32,family:e&&!da?B.replace(e[0],""):B,version:e?e[1]:null,toString:function(){var M=this.version;return this.family+(M&&!da?" "+M:"")+(64==this.architecture?" 64-bit":"")}}}(e=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(Z))&&!/\bi686\b/i.test(Z)?(B&&(B.architecture=64,B.family=B.family.replace(RegExp(" *"+e),"")),A&&(/\bWOW64\b/i.test(d)||V&&/\w(?:86|32)$/.test(F.cpuClass||F.platform)&&!/\bWin64; x64\b/i.test(d))&&
y.unshift("32-bit")):B&&/^OS X/.test(B.family)&&"Chrome"==A&&39<=parseFloat(p)&&(B.architecture=64);d||(d=null);v={};v.description=d;v.layout=G&&G[0];v.manufacturer=O;v.name=A;v.prerelease=aa;v.product=H;v.ua=d;v.version=A&&p;v.os=B||{architecture:null,family:null,version:null,toString:function(){return"null"}};v.parse=l;v.toString=function(){return this.description||""};v.version&&y.unshift(p);v.name&&y.unshift(A);B&&A&&(B!=String(B).split(" ")[0]||B!=A.split(" ")[0]&&!H)&&y.push(H?"("+B+")":"on "+
B);y.length&&(v.description=y.join(" "));return v}var k={"function":!0,object:!0},n=k[typeof window]&&window||this,q=k[typeof exports]&&exports;k=k[typeof module]&&module&&!module.nodeType&&module;var C=q&&k&&"object"==typeof global&&global;!C||C.global!==C&&C.window!==C&&C.self!==C||(n=C);var x=Math.pow(2,53)-1,t=/\bOpera/;C=Object.prototype;var u=C.hasOwnProperty,E=C.toString,J=l();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(n.platform=J,define(function(){return J})):q&&
k?g(J,function(d,w){q[w]=d}):n.platform=J}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],f=0;f<a.length;f++){var b=document.createElement("meta");b.name=a[f].name;b.content=a[f].content;var g=window.document.head.querySelector('meta[name="'+b.name+'"]');g&&g.parentNode.removeChild(g);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,f=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===f&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});
!function(){var a="undefined"!=typeof window&&void 0!==window.document?window.document:{},f="undefined"!=typeof module&&module.exports,b=function(){for(var m,h=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],c=0,l=h.length,k={};c<l;c++)if((m=h[c])&&m[1]in a){for(c=0;c<m.length;c++)k[h[0][c]]=m[c];return k}return!1}(),g={change:b.fullscreenchange,error:b.fullscreenerror},r={request:function(m){return new Promise(function(h,c){var l=function(){this.off("change",
l);h()}.bind(this);this.on("change",l);m=m||a.documentElement;Promise.resolve(m[b.requestFullscreen]())["catch"](c)}.bind(this))},exit:function(){return new Promise(function(m,h){if(this.isFullscreen){var c=function(){this.off("change",c);m()}.bind(this);this.on("change",c);Promise.resolve(a[b.exitFullscreen]())["catch"](h)}else m()}.bind(this))},toggle:function(m){return this.isFullscreen?this.exit():this.request(m)},onchange:function(m){this.on("change",m)},onerror:function(m){this.on("error",m)},
on:function(m,h){var c=g[m];c&&a.addEventListener(c,h,!1)},off:function(m,h){var c=g[m];c&&a.removeEventListener(c,h,!1)},raw:b};b?(Object.defineProperties(r,{isFullscreen:{get:function(){return!!a[b.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[b.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[b.fullscreenEnabled]}}}),f?module.exports=r:window.screenfull=r):f?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}}();
var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");if(-1!==navigator.userAgent.toLowerCase().indexOf("iphone"))return s_bIsIphone=!0;for(;a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var f=a.toLowerCase(),b=window.document,g=b.documentElement;if(void 0===window["inner"+a])a=g["client"+a];else if(window["inner"+a]!=g["client"+a]){var r=b.createElement("body");r.id="vpw-test-b";r.style.cssText="overflow:scroll";var m=b.createElement("div");m.id="vpw-test-d";m.style.cssText="position:absolute;top:-1000px";m.innerHTML="<style>@media("+f+":"+g["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+f+":7px!important}}</style>";r.appendChild(m);g.insertBefore(r,b.head);
a=7==m["offset"+a]?g["client"+a]:window["inner"+a];g.removeChild(r)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var f=getSize("Width");s_bFocus&&_checkOrientation(f,a);var b=Math.min(a/CANVAS_HEIGHT,f/CANVAS_WIDTH),g=Math.round(CANVAS_WIDTH*b);b=Math.round(CANVAS_HEIGHT*b);if(b<a){var r=a-b;b+=r;g+=CANVAS_WIDTH/CANVAS_HEIGHT*r}else g<f&&(r=f-g,g+=r,b+=CANVAS_HEIGHT/CANVAS_WIDTH*r);r=a/2-b/2;var m=f/2-g/2,h=CANVAS_WIDTH/g;if(m*h<-EDGEBOARD_X||
r*h<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),f/(CANVAS_WIDTH-2*EDGEBOARD_X)),g=Math.round(CANVAS_WIDTH*b),b=Math.round(CANVAS_HEIGHT*b),r=(a-b)/2,m=(f-g)/2,h=CANVAS_WIDTH/g;s_iOffsetX=-1*m*h;s_iOffsetY=-1*r*h;0<=r&&(s_iOffsetY=0);0<=m&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone&&s_oStage?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*g,s_oStage.canvas.height=
2*b,canvas.style.width=g+"px",canvas.style.height=b+"px",s_oStage.scaleX=s_oStage.scaleY=2*Math.min(g/CANVAS_WIDTH,b/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",g+"px"),$("#canvas").css("height",b+"px")):s_oStage&&(s_oStage.canvas.width=g,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(g/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>r||(r=(a-b)/2);$("#canvas").css("top",r+"px");$("#canvas").css("left",m+"px");fullscreenHandler()}}
function _checkOrientation(a,f){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>f?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,f,b){var g=new createjs.Bitmap(a),r=new createjs.Shape;f&&b?r.graphics.beginFill("#fff").drawRect(0,0,f,b):r.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);g.hitArea=r;return g}function createSprite(a,f,b,g,r,m){a=null!==f?new createjs.Sprite(a,f):new createjs.Sprite(a);f=new createjs.Shape;f.graphics.beginFill("#000000").drawRect(-b,-g,r,m);a.hitArea=f;return a}
(function(){function a(b){var g={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in g?document.body.className=g[b.type]:(document.body.className=this[f]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var f="hidden";f in document?document.addEventListener("visibilitychange",a):(f="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(f="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(f="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function randomFloatBetween(a,f,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(f-a),f).toFixed(b))}
function shuffle(a){for(var f=a.length,b,g;0!==f;)g=Math.floor(Math.random()*f),--f,b=a[f],a[f]=a[g],a[g]=b;return a}function formatTime(a){a/=1E3;var f=Math.floor(a/60);a=Math.floor(a-60*f);var b="";b=10>f?b+("0"+f+":"):b+(f+":");return 10>a?b+("0"+a):b+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var f=Array.prototype.slice.call(arguments);return a.sort(function(b,g){for(var r=f.slice(),m=r.shift();b[m]==g[m]&&r.length;)m=r.shift();return b[m]==g[m]?0:b[m]>g[m]?1:-1})};function roundDecimal(a,f){var b=Math.pow(10,f);return Math.round(b*a)/b}function tweenVectors(a,f,b,g){g.set(a.getX()+b*(f.getX()-a.getX()),a.getY()+b*(f.getY()-a.getY()));return g}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var f=document.createEvent("MouseEvents");f.initEvent("click",!0,!0);a.dispatchEvent(f)}}};function playSound(a,f,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(f),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}
function setVolume(a,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(f)}function setMute(a,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(f)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var f=window.location.search.substring(1).split("&"),b=0;b<f.length;b++){var g=f[b].split("=");if(g[0]==a)return g[1]}}
function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});var s_szGameID="09d7fcd594154dd9a97b3dbcb6a33999";
window.GD_OPTIONS={gameId:s_szGameID,onEvent:function(a){switch(a.name){case "SDK_GAME_START":s_oMain&&s_oMain.startUpdate();break;case "SDK_GAME_PAUSE":s_oMain&&s_oMain.stopUpdate()}}};(function(a,f,b){var g=a.getElementsByTagName(f)[0];a.getElementById(b)||(a=a.createElement(f),a.id=b,a.src="/main.min.js",g.parentNode.insertBefore(a,g))})(document,"script","gamedistribution-jssdk");
function CSpriteLibrary(){var a={},f,b,g,r,m,h;this.init=function(c,l,k){f={};g=b=0;r=c;m=l;h=k};this.addSprite=function(c,l){if(a.hasOwnProperty(c))return!1;var k=new Image;a[c]=f[c]={szPath:l,oSprite:k,bLoaded:!1};b++;return!0};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){b=0;m.call(h)};this._onSpriteLoaded=function(){r.call(h);++g===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in f)f[c].oSprite.oSpriteLibrary=this,
f[c].oSprite.szKey=c,f[c].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},f[c].oSprite.onerror=function(l){var k=l.currentTarget;setTimeout(function(){f[k.szKey].oSprite.src=f[k.szKey].szPath},500)},f[c].oSprite.src=f[c].szPath};this.setLoaded=function(c){a[c].bLoaded=!0};this.isLoaded=function(c){return a[c].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,DISABLE_SOUND_MOBILE=!1,EDGEBOARD_X=0,EDGEBOARD_Y=84,FONT_GAME="impactregular",FONT_GAME2="Digital-7",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,TOTAL_SCENES=5,BALL_SIZE=73,BALL_ROTATION_SPEED=3,CAM_DISTANCE=1,PLAYER_HEIGHT=768,PLAYER_WIDTH=408,CART_HEIGHT=329,CART_WIDTH=356,SHOTGUI_SIZE=229,SHOTBALL_SIZE=48,CART_DEPTH_INDEX,ERROR_MULT,TIME_AVAILABLE,NUM_SHOT_PER_SCENE=
5,SELECTOR_SPEED,POINT_FOR_BALL,POINT_FOR_SPECIAL_BALL,SOUNDTRACK_VOLUME_IN_GAME=0,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
function CPreloader(){var a,f,b,g,r,m,h,c,l,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren();l.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(n);n=s_oSpriteLibrary.getSprite("200x200");h=createBitmap(n);h.regX=.5*n.width;h.regY=.5*n.height;h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-180;k.addChild(h);c=new createjs.Shape;c.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(h.x-100,h.y-100,200,200,10);k.addChild(c);h.mask=c;
n=s_oSpriteLibrary.getSprite("progress_bar");g=createBitmap(n);g.x=CANVAS_WIDTH/2-n.width/2;g.y=CANVAS_HEIGHT/2+50;k.addChild(g);a=n.width;f=n.height;r=new createjs.Shape;r.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(g.x,g.y,1,f);k.addChild(r);g.mask=r;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+100;b.textBaseline="alphabetic";b.textAlign="center";k.addChild(b);n=s_oSpriteLibrary.getSprite("but_start");l=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2,n,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 40",k);l.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);l.setVisible(!1);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(m);createjs.Tween.get(m).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(m);k.removeChild(m)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(n){b.text=n+"%";100===n&&(s_oMain._onRemovePreloader(),b.visible=
!1,g.visible=!1);r.graphics.clear();n=Math.floor(n*a/100);r.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(g.x,g.y,n,f)};this._init()}
function CMain(a){ERROR_MULT=a.errorMultiplier;TIME_AVAILABLE=a.timeAvailable;SELECTOR_SPEED=a.selectorSpeed;POINT_FOR_BALL=a.point_per_ball;POINT_FOR_SPECIAL_BALL=a.point_per_special_ball;var f=!1,b=0,g=0,r=STATE_LOADING,m,h;this.initContainer=function(){s_oStage=new createjs.Stage("canvas");s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.framerate=30;createjs.Ticker.addEventListener("tick",
this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;m=new CPreloader;f=!0};this.soundLoaded=function(){b++;m.refreshLoader(Math.floor(b/g*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"us_bounce",loop:!1,volume:1,ingamename:"us_bounce"});s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",
filename:"us_buzzer",loop:!1,volume:1,ingamename:"us_buzzer"});s_aSoundsInfo.push({path:"./sounds/",filename:"us_cheer",loop:!1,volume:1,ingamename:"us_cheer"});s_aSoundsInfo.push({path:"./sounds/",filename:"us_crowd",loop:!0,volume:1,ingamename:"us_crowd"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});g+=s_aSoundsInfo.length;s_aSounds=[];for(var c=0;c<s_aSoundsInfo.length;c++)this.tryToLoadSound(s_aSoundsInfo[c],!1)};this.tryToLoadSound=function(c,
l){setTimeout(function(){s_aSounds[c.ingamename]=new Howl({src:[c.path+c.filename+".mp3"],autoplay:!1,preload:!0,loop:c.loop,volume:c.volume,onload:s_oMain.soundLoaded,onloaderror:function(k,n){for(var q=0;q<s_aSoundsInfo.length;q++)if(k===s_aSounds[s_aSoundsInfo[q].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[q],!0);break}},onplayerror:function(k){for(var n=0;n<s_aSoundsInfo.length;n++)if(k===s_aSounds[s_aSoundsInfo[n].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[n].ingamename].once("unlock",
function(){s_aSounds[s_aSoundsInfo[n].ingamename].play();"soundtrack"===s_aSoundsInfo[n].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},l?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("ball_1","./sprites/ball_1.png");s_oSpriteLibrary.addSprite("ball_2","./sprites/ball_2.png");s_oSpriteLibrary.addSprite("bg_help",
"./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("cart_back","./sprites/cart_back.png");s_oSpriteLibrary.addSprite("cart_front","./sprites/cart_front.png");s_oSpriteLibrary.addSprite("field_camera_1","./sprites/field_camera_1.jpg");s_oSpriteLibrary.addSprite("field_camera_2","./sprites/field_camera_2.jpg");
s_oSpriteLibrary.addSprite("field_camera_3","./sprites/field_camera_3.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("shot_ball","./sprites/shot_ball.png");s_oSpriteLibrary.addSprite("shot_gui","./sprites/shot_gui.png");s_oSpriteLibrary.addSprite("time_panel","./sprites/time_panel.png");s_oSpriteLibrary.addSprite("shadow","./sprites/shadow.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_credits",
"./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var c=0;131>=c;c++){var l=9>=c?"00"+c:99>=c?"0"+c:c;var k="pl"+c;l="./sprites/player_frames/new_player_0000"+l+".png";s_oSpriteLibrary.addSprite(k,l)}for(c=1;36>=c;c++)l=9>=c?"00"+c:99>=c?"0"+c:c,k="bsk"+c,l="./sprites/basket/basket_0"+l+".png",s_oSpriteLibrary.addSprite(k,l);g+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;m.refreshLoader(Math.floor(b/
g*100))};this._onAllImagesLoaded=function(){};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this._onRemovePreloader=function(){try{checkMoreGames(s_szGameID,"bottom-left",["sport","multiplayer"],[],-1,"red")}catch(c){}m.unload();s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){try{showMoreGames()}catch(c){}new CMenu;r=STATE_MENU};this.gotoGame=function(){h=new CGame;r=STATE_GAME};this.gotoHelp=function(){_oHelp=
new CHelp;r=STATE_HELP};this.stopUpdate=function(){f=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();f=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(c){if(f){var l=(new Date).getTime();s_iTimeElaps=l-s_iPrevTime;s_iCntTime+=s_iTimeElaps;
s_iCntFps++;s_iPrevTime=l;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);r===STATE_GAME&&h.update(l);s_oStage.update(c)}};s_oMain=this;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings,s_oSoundTrack=null,s_bFullscreen=!1,s_aSounds,s_aSoundsInfo;
function CTextButton(a,f,b,g,r,m,h,c){var l,k,n,q,C,x,t,u,E,J;this._init=function(d,w,z,v,y,F,p){l=!1;k=1;n=[];q=[];J=createBitmap(z);u=new createjs.Container;u.x=d;u.y=w;u.regX=z.width/2;u.regY=z.height/2;s_bMobile||(u.cursor="pointer");u.addChild(J,E);c.addChild(u);E=new CTLText(u,30,25,z.width-60,z.height-50,p,"center",F,y,1.1,0,0,v,!0,!0,!1,!1);this._initListener()};this.unload=function(){u.off("mousedown",C);u.off("pressup",x);c.removeChild(u)};this.setVisible=function(d){u.visible=d};this.setAlign=
function(d){E.textAlign=d};this.setTextX=function(d){E.x=d};this.setScale=function(d){k=u.scaleX=u.scaleY=d};this.enable=function(){l=!1};this.disable=function(){l=!0};this._initListener=function(){C=u.on("mousedown",this.buttonDown);x=u.on("pressup",this.buttonRelease)};this.addEventListener=function(d,w,z){n[d]=w;q[d]=z};this.addEventListenerWithParams=function(d,w,z,v){n[d]=w;q[d]=z;t=v};this.buttonRelease=function(){l||(playSound("click",1,!1),u.scaleX=k,u.scaleY=k,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(q[ON_MOUSE_UP],
t))};this.buttonDown=function(){l||(u.scaleX=.9*k,u.scaleY=.9*k,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN]))};this.setPosition=function(d,w){u.x=d;u.y=w};this.tweenPosition=function(d,w,z,v,y,F,p){createjs.Tween.get(u).wait(v).to({x:d,y:w},z,y).call(function(){void 0!==F&&F.call(p)})};this.changeText=function(d){E.refreshText(d)};this.setX=function(d){u.x=d};this.setY=function(d){u.y=d};this.getButtonImage=function(){return u};this.getX=function(){return u.x};this.getY=function(){return u.y};
this.getSprite=function(){return u};this.getScale=function(){return u.scaleX};this._init(a,f,b,g,r,m,h)}
function CGfxButton(a,f,b){var g,r,m,h,c,l=[],k,n,q;this._init=function(C,x,t){g=!1;h=[];c=[];r=t.width;m=t.height;q=createBitmap(t);q.x=C;q.y=x;q.regX=t.width/2;q.regY=t.height/2;s_bMobile||(q.cursor="pointer");s_oStage.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown",k);q.off("pressup",n);s_oStage.removeChild(q)};this.setVisible=function(C){q.visible=C};this._initListener=function(){k=q.on("mousedown",this.buttonDown);n=q.on("pressup",this.buttonRelease)};this.addEventListener=
function(C,x,t){h[C]=x;c[C]=t};this.addEventListenerWithParams=function(C,x,t,u){h[C]=x;c[C]=t;l=u};this.buttonRelease=function(){g||(playSound("click",1,!1),q.scaleX=1,q.scaleY=1,h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(c[ON_MOUSE_UP],l))};this.buttonDown=function(){g||(q.scaleX=.9,q.scaleY=.9,h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN],l))};this.setPosition=function(C,x){q.x=C;q.y=x};this.setX=function(C){q.x=C};this.setY=function(C){q.y=C};this.enable=function(){g=!1;q.filters=[];q.cache(0,
0,r,m)};this.disable=function(){g=!0;var C=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);q.filters=[new createjs.ColorMatrixFilter(C)];q.cache(0,0,r,m)};this.getButtonImage=function(){return q};this.getX=function(){return q.x};this.getY=function(){return q.y};this._init(a,f,b);return this}
function CToggle(a,f,b,g,r){var m,h,c,l,k,n,q;this._init=function(x,t,u,E){h=[];c=[];var J=new createjs.SpriteSheet({images:[u],frames:{width:u.width/2,height:u.height,regX:u.width/2/2,regY:u.height/2},animations:{state_true:[0],state_false:[1]}});m=E;q=createSprite(J,"state_"+m,u.width/2/2,u.height/2,u.width/2,u.height);q.x=x;q.y=t;q.stop();C.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown",l);q.off("pressup",k);s_bMobile||q.off("mouseover",n);C.removeChild(q)};this._initListener=
function(){l=q.on("mousedown",this.buttonDown);k=q.on("pressup",this.buttonRelease);s_bMobile||(n=q.on("mouseover",this.buttonOver))};this.addEventListener=function(x,t,u){h[x]=t;c[x]=u};this.setActive=function(x){m=x;q.gotoAndStop("state_"+m)};this.buttonRelease=function(){q.scaleX=1;q.scaleY=1;playSound("click",1,!1);m=!m;q.gotoAndStop("state_"+m);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(c[ON_MOUSE_UP],m)};this.buttonDown=function(){q.scaleX=.9;q.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN])};
this.buttonOver=function(x){s_bMobile||(x.target.cursor="pointer")};this.setPosition=function(x,t){q.x=x;q.y=t};var C=r;this._init(a,f,b,g)}
function CMenu(){var a,f,b,g,r,m,h,c,l,k,n,q=null,C=null,x;this._init=function(){h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(h);var t=s_oSpriteLibrary.getSprite("but_play");c=new CTextButton(CANVAS_WIDTH-300,CANVAS_HEIGHT/2+50,t,TEXT_PLAY,FONT_GAME,"#ffffff",60,s_oStage);c.addEventListener(ON_MOUSE_UP,this._onButPlay,this,!1);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),r=CANVAS_WIDTH-t.width/4-10,m=t.height/2+10,l=new CToggle(r,
m,t,s_bAudioActive,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);t=s_oSpriteLibrary.getSprite("but_credits");b=t.height/2+10;g=t.height/2+10;k=new CGfxButton(b,g,t,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onCredits,this);t=window.document;var u=t.documentElement;q=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;C=t.exitFullscreen||t.mozCancelFullScreen||t.webkitExitFullscreen||t.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);
q&&screenfull.isEnabled&&(t=s_oSpriteLibrary.getSprite("but_fullscreen"),a=b+t.width/2+10,f=g,n=new CToggle(a,f,t,s_bFullscreen,s_oStage),n.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));x=new createjs.Shape;x.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(x);createjs.Tween.get(x).to({alpha:0},1E3).call(function(){x.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY);setVolume("soundtrack",1)};this.refreshButtonPos=function(t,u){!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||l.setPosition(r-t,u+m);q&&screenfull.isEnabled&&n.setPosition(a+s_iOffsetX,f+s_iOffsetY);k.setPosition(b+t,u+g)};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;q&&screenfull.isEnabled&&n.unload();s_oStage.removeAllChildren();s_oMenu=null};this.resetFullscreenBut=function(){n.setActive(s_bFullscreen)};this._onCredits=function(){new CCreditsPanel};this._onButPlay=function(){"undefined"!==typeof gdsdk&&"undefined"!==gdsdk.showAd&&
gdsdk.showAd();try{hideMoreGames()}catch(t){}this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?C.call(window.document):q.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CHelpPanel(){var a,f,b;this._init=function(){b=new createjs.Container;s_oStage.addChild(b);a=new createBitmap(s_oSpriteLibrary.getSprite("bg_help"));b.addChild(a);(new CTLText(b,CANVAS_WIDTH/2-260,220,520,120,48,"center","#FFCC00",FONT_GAME,1,0,0,s_bMobile?TEXT_HELP_MOBILE:TEXT_HELP,!0,!0,!0,!1)).setShadow("#000",2,2,2);(new CTLText(b,260,510,130,28,28,"center","#FFCC00",FONT_GAME,1,0,0,"1 "+TEXT_POINT,!0,!0,!1,!1)).setShadow("#000",2,2,2);(new CTLText(b,410,510,130,28,28,"center","#FFCC00",
FONT_GAME,1,0,0,"2 "+TEXT_POINTS,!0,!0,!1,!1)).setShadow("#000",2,2,2);var g=s_oSpriteLibrary.getSprite("but_play");f=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-140,g,TEXT_PLAY,FONT_GAME,"#fff",60,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.unload=function(){f.unload();b.removeAllChildren()};this._onExit=function(){this.unload();s_oGame.exitFromHelp()};this._init()}
function CGame(){var a=!1,f=!1,b=!1,g=!0,r=!1,m=!1,h,c,l,k=0,n=0,q=0,C,x,t=[],u,E,J,d=null,w,z,v,y,F;this._init=function(){h=0;c=1;l=NUM_SHOT_PER_SCENE;x=TIME_AVAILABLE;u=new CANNON.World;u.gravity.set(0,0,-400);u.broadphase=new CANNON.NaiveBroadphase;u.solver.iterations=5;v=new CANNON.Material;y=new CANNON.Material;F=new CANNON.Material;var p=new CANNON.ContactMaterial(v,v,{friction:.2,restitution:.55}),L=new CANNON.ContactMaterial(y,v,{friction:.05,restitution:.35}),U=new CANNON.ContactMaterial(y,
F,{friction:.25,restitution:.5});u.addContactMaterial(p);u.addContactMaterial(L);u.addContactMaterial(U);p=new CANNON.Plane;L=new CANNON.Body({mass:0,material:v});L.addShape(p);u.add(L);z=new CSceneStatic(u,c,v,F);p=z.getCartCoords();w=new CPlayer(this,p);for(L=0;L<l;L++)t.push(new CBall(u,v,v,c,L,p));E=new CInterface(this);J=new CHelpPanel;setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);playSound("us_crowd",1,!0);$(s_oMain).trigger("start_level",1)};this.unload=function(){$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session");0<k&&$(s_oMain).trigger("share_event",k);stopSound("us_crowd");for(var p=u.bodies.length,L=0;L<p;L++)u.remove(u.bodies[0]);u=null;createjs.Tween.removeAllTweens();s_oStage.removeAllEventListeners();s_oStage.removeAllChildren();E.unload();null!==d&&d.unload();s_oMain.gotoMenu()};this.exitFromHelp=function(){J.unload();h=1};this.getState=function(){return _oGameStates[void 0]};this.ballWaitToThrow=function(){0<l&&t[l-1].waitToThrow()};this.update=function(p){1<h&&(void 0===
C?C=p:(x=Math.floor(TIME_AVAILABLE-(p-C)),0<=x?(E.updateTime(x),z.updateTime(x)):(playSound("us_buzzer",1,!1),d=new CEndPanel(x,k,n,this),h=-1)));1===h&&(q++,w.idle1(),30<q&&(h=2));if(2===h){E.listenForClick();w.grab1();if(w.isBallGrabbed()&&!b)for(b=!0,t[l-1].grab(w.getPlCoords()),p=0;p<l-1;p++)t[p].slide();E.isVectorAquired().state&&(h=3)}3===h&&(a||(a=!0,t[l-1].throwingBall(w.getPlCoords(),E.isVectorAquired().vector,t[l-1]),t[l-1].update()),w.throwing(c)&&(h=4,g=!0,m=r=a=!1));if(4===h){g&&(b=g=
!1,w.newBall(),z.newBall(),l--,n++,E.updateShots(n));t[l].update();p=z.updateBasket(t[l].getPosition());!0===p?(r=!0,k=0===t[l].getCartPosition()?k+POINT_FOR_SPECIAL_BALL:k+POINT_FOR_BALL,E.updateScore(k),playSound("us_cheer",1,!1)):!1===p&&!1===r&&(m=!0);!0===r?(r=z.scored(),m=!1):m&&(m=z.rimCollision());t[l].touchGround();if(0<l){if(w.grab2(),w.isBallGrabbed()&&!b)for(b=!0,t[l-1].grab(w.getPlCoords()),p=0;p<l-1;p++)t[p].slide()}else w.endTurn();t[l].touchedGround()&&(f||(E.newBall(),f=!0),0<l?(E.listenForClick(),
E.isVectorAquired().state&&(h=3,f=!1)):0===l&&(f=!1,h=5))}if(5===h)if(c++,5>=c){l=NUM_SHOT_PER_SCENE;w.endTurn();z.nextScene();w.nextScene(z.getCartCoords());for(p=0;p<l;p++)t[p].unload(),t[p]=new CBall(u,v,v,c,p,z.getCartCoords());h=1}else d=new CEndPanel(x,k,n,this),h=-1};s_oGame=this;this._init()}var s_oGame;
function CBall(a,f,b,g,r,m){var h=[[-1.324419465111331,.07007920010441403,.1938814229049522,.1928501356834461,-.2649754991389736,-.29199768911624474,-.9738954395935614,-.9687151293457442,.00813866187260608,1.8973661726282403,-.15703993365948804,-.1562046123872247,172.14460555118495,-57.92280926049329,268.64013255353115,275.1899143092173],[-1.0311847252524577,-.17599844916970192,-.6427545415461143,-.6393356242752912,.8719967238119737,-.26330126009450605,-.7552979557156582,-.7512804014885001,.025392432048756682,
1.8946950915444967,-.16466751447142178,-.16379162084052554,74.75179565415395,-37.2124724898568,323.023333753347,329.2838423047125],[-.04192064711782405,-.28804391554765474,-.9934914290013894,-.9882068844583713,1.3500256223076117,-.017671886269370676,-.030155903522676906,-.02999549930503738,.006203995474932445,1.8991816460801592,-.15096085318711913,-.15015786754513807,6.84660099873786,-40.15800737796026,335.8181997013088,342.0106502533296],[1.0287322954933102,-.20296283656350578,-.6427545605150148,
-.6393356431432929,.8752566449130996,.2404296293623392,.7552979421456383,.7512803879906613,-8.671184282911734E-4,1.895038730402846,-.1646675026722602,-.16379160910412566,-75.22073485514608,-35.249324074836075,323.0233348288672,329.2838433745118],[1.3232711036898168,-.00901517234163781,.201487851298251,.20041610423131065,-.2666922478682122,.28881907281462693,.9738954354986644,.9687151252726287,.04684016896142928,1.8991247445227672,-.14715365255419113,-.14637091803943836,-176.51195787275645,-53.18780012690175,
267.37304986600344,273.9295714431983]],c=!1,l=!1,k=!1,n=!1,q=0,C=[0,new CANNON.Vec3(97,150,86),new CANNON.Vec3(178,80,86),new CANNON.Vec3(195,-26,86),new CANNON.Vec3(130,-110,86),new CANNON.Vec3(112,-150,87)],x=[0,new CANNON.Vec3(97,150,78.5),new CANNON.Vec3(178,80,78.5),new CANNON.Vec3(195,-26,78.5),new CANNON.Vec3(130,-110,78.5),new CANNON.Vec3(112,-150,79.5)],t=[0,new CANNON.Vec3(-1292.5,-5287.5,6697.5),new CANNON.Vec3(-3995,-2702.5,6697.5),new CANNON.Vec3(-4935,940,6580),new CANNON.Vec3(-2398.5,
4036.5,6552),new CANNON.Vec3(-1755,5206.5,6669)],u=m.x-BALL_SIZE;m=m.y-.4*CANVAS_HEIGHT;var E={x:0,y:0},J=0;this._oSphereBody;this._oStandBody;this._oSprite;this._oSpriteShadow;this._oContainer=void 0;this._v2SlideDestination={x:0,y:0};var d=new CANNON.Sphere(7);this._oSphereBody=new CANNON.Body({mass:1,material:f});this._oSphereBody.position.copy(C[g]);this._oSphereBody.addShape(d);f=new CANNON.Box(new CANNON.Vec3(2.5,2.5,.5));this._oStandBody=new CANNON.Body({mass:0,material:b});this._oStandBody.position.copy(x[g]);
this._oStandBody.addShape(f);this._oSpriteShadow=createBitmap(s_oSpriteLibrary.getSprite("shadow"));this._oSpriteShadow.regX=52;this._oSpriteShadow.regY=22;this._oSpriteShadow.visible=!1;this._oSprite=createBitmap(s_oSpriteLibrary.getSprite(0===r?"ball_2":"ball_1"));this._oSprite.regX=BALL_SIZE/2;this._oSprite.regY=BALL_SIZE/2;this._oSprite.x=5>g?u-r*BALL_SIZE*.75:u+(r-(NUM_SHOT_PER_SCENE-1))*BALL_SIZE*.75;this._oSprite.y=m;this._oContainer=new createjs.Container;this._oContainer.addChild(this._oSprite,
this._oSpriteShadow);s_oStage.addChildAt(this._oContainer,CART_DEPTH_INDEX+1);this.unload=function(){a.remove(this._oSphereBody);a.remove(this._oStandBody);s_oStage.removeChild(this._oContainer)};this.update=function(){if(!k){a.step(1/30);J=E.x;E=this._projCoordScaling(this._oSphereBody.position);var w=E.x-J,z=E.diam/BALL_SIZE;1<z&&(z=1);this._oSprite.x=E.x;this._oSprite.y=E.y;this._oSprite.scaleY=this._oSprite.scaleX=z;q+=w*BALL_ROTATION_SPEED;this._oSprite.rotation=q;this._oSpriteShadow.visible=
!0;this._oSpriteShadow.x=E.shadowX;this._oSpriteShadow.y=E.shadowY;this._oSpriteShadow.scaleX=this._oSpriteShadow.x.scaleY=.75*z;this._oSpriteShadow.alpha=this._oSprite.y/CANVAS_HEIGHT*.66+.33}};this.grab=function(w){c||(c=!0,createjs.Tween.removeTweens(this._oSprite),5>g?createjs.Tween.get(this._oSprite).to({x:w.x,y:w.y},80,createjs.Ease.cubicIn):createjs.Tween.get(this._oSprite).to({x:w.x+100,y:w.y},80,createjs.Ease.cubicIn))};this.slide=function(){q-=75;5>g?createjs.Tween.get(this._oSprite).to({x:this._oSprite.x-
.8*BALL_SIZE,rotation:q},500,createjs.Ease.linear):createjs.Tween.get(this._oSprite).to({x:this._oSprite.x+.8*BALL_SIZE,rotation:q},500,createjs.Ease.linear)};this.waitToThrow=function(){if(!l&&!k){l=!0;var w=this;createjs.Tween.get(this._oSprite).to({y:this._oSprite.y+7},450,createjs.Ease.linear).call(function(){createjs.Tween.get(w._oSprite).to({y:w._oSprite.y-7},450,createjs.Ease.linear).call(function(){l=!1})},w)}};this._projCoord=function(w){var z=w.x,v=w.y,y=z;w=w.z;var F=h[g-1],p=1/(F[3]*y+
F[7]*v+F[11]*w+F[15]);z=(F[0]*y+F[4]*v+F[8]*w+F[12])*p;v=(F[1]*y+F[5]*v+F[9]*w+F[13])*p;z=(z+1)*CANVAS_WIDTH/2;v=(-v+1)*CANVAS_HEIGHT/2;return{x:z,y:v}};this._projCoordScaling=function(w){var z=this._projCoord(new CANNON.Vec3(w.x,w.y,w.z+7)),v=this._projCoord(new CANNON.Vec3(w.x,w.y,w.z-7));w=this._projCoord(new CANNON.Vec3(w.x,w.y,0));return{x:(z.x+v.x)/2,y:(z.y+v.y)/2,diam:Math.abs(z.y-v.y),shadowX:w.x,shadowY:w.y}};this.throwingBall=function(w,z,v){var y,F,p=this;5>g?(y=w.x-40,F=w.y-172):(y=w.x+
145,F=w.y-172);k||(k=!0,createjs.Tween.removeTweens(this._oSprite),createjs.Tween.get(this._oSprite).to({x:y,y:F},100,createjs.Ease.linear).call(function(){var L;1===g?L=new CANNON.Vec3(t[1].x-z.x*ERROR_MULT,t[1].y+z.y*ERROR_MULT,t[1].z):2===g?L=new CANNON.Vec3(t[2].x-z.x*ERROR_MULT,t[2].y+z.y*ERROR_MULT,t[2].z):3===g?L=new CANNON.Vec3(t[3].x+z.y*ERROR_MULT,t[3].y+z.x*ERROR_MULT,t[3].z):4===g?L=new CANNON.Vec3(t[4].x+z.x*ERROR_MULT,t[4].y-z.y*ERROR_MULT,t[4].z):5===g&&(L=new CANNON.Vec3(t[5].x+z.x*
ERROR_MULT,t[5].y-z.y*ERROR_MULT,t[5].z));a.add(v._oSphereBody);a.add(v._oStandBody);p._oSphereBody.applyForce(L,p._oSphereBody.position)},p),p.update(),k=!1)};this.touchGround=function(){var w=this;7.01>=this._oSphereBody.position.z&&!1===n&&(playSound("us_bounce",1,!1),n=!0,createjs.Tween.get(w._oContainer).to({alpha:0},1E3,createjs.Ease.circIn).call(function(){w.unload()},w))};this.touchedGround=function(){return n};this.getPosition=function(){return this._oSphereBody.position};this.getCartPosition=
function(){return r}}
function CInterface(a){var f,b,g,r,m,h,c,l=!0,k=!1,n=!1,q=!1,C=!1,x=!1,t=void 0,u=void 0,E=SHOTGUI_SIZE/3,J=.85*CANVAS_WIDTH,d=.45*CANVAS_HEIGHT,w,z,v,y,F,p,L,U,W,Q,Y,R,X,S=null,P=null;this.init=function(D){w=D;D=s_oSpriteLibrary.getSprite("shot_gui");F=createBitmap(D);F.regX=SHOTGUI_SIZE/2;F.regY=SHOTGUI_SIZE/2;F.x=J;F.y=d;s_oStage.addChild(F);R=new createjs.Container;R.x=80;s_oStage.addChild(R);D=s_oSpriteLibrary.getSprite("time_panel");p=createBitmap(D);R.addChild(p);W=new CTLText(R,p.x+5,40,D.width-
10,24,24,"center","#ffde00",FONT_GAME2,1,0,0,TEXT_TIME_LEFT+" "+formatTime(TIME_AVAILABLE),!0,!0,!1,!1);W.setShadow("#000000",3,3,4);Q=new CTLText(R,p.x+5,68,D.width-10,30,30,"center","#ffde00",FONT_GAME2,1,0,0,TEXT_SCORE+" 0",!0,!0,!1,!1);Q.setShadow("#000000",3,3,4);Y=new CTLText(R,p.x+5,100,D.width-10,30,30,"center","#ffde00",FONT_GAME2,1,0,0,TEXT_SHOTS+" 0",!0,!0,!1,!1);Y.setShadow("#000000",3,3,4);v=createBitmap(s_oSpriteLibrary.getSprite("shot_ball"));v.regX=SHOTBALL_SIZE/2;v.regY=SHOTBALL_SIZE/
2;v.x=J-100;v.y=d;s_oStage.addChild(v);y=createBitmap(s_oSpriteLibrary.getSprite("shot_ball"));y.regX=SHOTBALL_SIZE/2;y.regY=SHOTBALL_SIZE/2;y.x=J;y.y=d-100;y.visible=!1;s_oStage.addChild(y);z=new createjs.Shape;z.graphics.beginFill("Black").drawRect(0,75,CANVAS_WIDTH,CANVAS_HEIGHT-75);z.alpha=.01;s_oStage.addChild(z);z.on("mousedown",this._handleClick,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)D=s_oSpriteLibrary.getSprite("audio_icon"),g=CANVAS_WIDTH-D.width/4-5,r=D.height/2+5,L=new CToggle(g,
r,D,s_bAudioActive,s_oStage),L.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);D=window.document;var e=D.documentElement;S=e.requestFullscreen||e.mozRequestFullScreen||e.webkitRequestFullScreen||e.msRequestFullscreen;P=D.exitFullscreen||D.mozCancelFullScreen||D.webkitExitFullscreen||D.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(S=!1);S&&screenfull.isEnabled&&(D=s_oSpriteLibrary.getSprite("but_fullscreen"),f=D.width/4+10,b=D.height/2+5,X=new CToggle(f,b,D,s_bFullscreen,s_oStage),X.addEventListener(ON_MOUSE_UP,
this._onFullscreenRelease,this));D=s_oSpriteLibrary.getSprite("but_exit");m=CANVAS_WIDTH-D.width/2-62;h=D.height/2+5;U=new CGfxButton(m,h,D);U.addEventListener(ON_MOUSE_UP,this._onExit,this);c=!1;!1===s_bMobile&&(document.onkeydown=this.onKeyDown,document.onkeyup=this.onKeyUp);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(D,e){U.setPosition(m-D,e+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||L.setPosition(g-D,e+r);S&&screenfull.isEnabled&&X.setPosition(f+s_iOffsetX,
b+s_iOffsetY);R.y=e};this.unload=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||L.unload();S&&screenfull.isEnabled&&X.unload();U.unload();document.onkeydown=null;s_oInterface=document.onkeyup=null};this.resetFullscreenBut=function(){X.setActive(s_bFullscreen)};this.updateTime=function(D){D=TEXT_TIME_LEFT+" "+formatTime(D);W.refreshText(D)};this.updateScore=function(D){Q.refreshText(TEXT_SCORE+" "+D)};this.updateShots=function(D){Y.refreshText(TEXT_SHOTS+" "+D)};this._handleClick=function(D){if(!l){l=
!1;if(!0===n)return n=!1,q=!0,t=Math.floor((v.x-J)/E*100)/100,y.visible=!0;!0===q&&(q=!1,u=Math.floor((y.y-d)/E*100)/100,k=!0)}};this.onKeyUp=function(D){c=!1};this.onKeyDown=function(D){if(!c){c=!0;D||(D=window.event);switch(D.keyCode){case 32:s_oInterface._handleClick()}D.preventDefault();return!1}};this.listenForClick=function(){l=!1;k||(!1===n&&!1===q&&(n=!0),this._animateShotBall());return!0};this._animateShotBall=function(){n?C?(v.x-=SELECTOR_SPEED,v.x<.85*CANVAS_WIDTH-E&&(C=!1)):(v.x+=SELECTOR_SPEED,
v.x>.85*CANVAS_WIDTH+E&&(C=!0)):q&&(x?(y.y-=SELECTOR_SPEED,y.y<.45*CANVAS_HEIGHT-E&&(x=!1)):(y.y+=SELECTOR_SPEED,y.y>.45*CANVAS_HEIGHT+E&&(x=!0)))};this.isVectorAquired=function(){return{state:k,vector:{x:t,y:u}}};this.newBall=function(){l=!0;x=C=q=n=k=!1;v.x=J-100;v.y=d;y.x=J;y.y=d-100;y.visible=!1};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){w.unload()};this._onFullscreenRelease=function(){s_bFullscreen?P.call(window.document):
S.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this.init(a)}var s_oInterface=null;
function CSceneStatic(a,f,b,g){var r=!0,m=!0,h=!1,c=0,l=f,k=[],n=[{},{x:.648*CANVAS_WIDTH,y:.88*CANVAS_HEIGHT/5},{x:.504*CANVAS_WIDTH,y:.79*CANVAS_HEIGHT/5},{x:2.39/5*CANVAS_WIDTH,y:.81*CANVAS_HEIGHT/5},{x:.442*CANVAS_WIDTH,y:.79*CANVAS_HEIGHT/5},{x:.292*CANVAS_WIDTH,y:.88*CANVAS_HEIGHT/5}],q=[{},{x:850,y:720},{x:700,y:720},{x:700,y:720},{x:700,y:720},{x:280,y:720}];var C=createBitmap(s_oSpriteLibrary.getSprite("field_camera_1"));C.scaleX=-1;C.x=CANVAS_WIDTH;s_oStage.addChild(C);var x=new createjs.Text("",
"27px "+FONT_GAME2,"Red");x.visible=!1;x.x=541;x.y=22;x.textBaseline="alphabetic";x.textAlign="center";s_oStage.addChild(x);var t=createBitmap(s_oSpriteLibrary.getSprite("cart_back"));s_oStage.addChild(t);var u=createBitmap(s_oSpriteLibrary.getSprite("cart_front"));s_oStage.addChild(u);CART_DEPTH_INDEX=s_oStage.getChildIndex(t);t.regX=u.regX=CART_WIDTH/2;t.regY=u.regY=CART_HEIGHT/2;t.x=u.x=q[1].x;t.y=u.y=q[1].y;f=new CANNON.Box(new CANNON.Vec3(.5,36,21));b=new CANNON.Body({mass:0,position:new CANNON.Vec3(48,
0,120),material:b});b.addShape(f);a.add(b);f=new CANNON.Box(new CANNON.Vec3(11,.5,.5));b=new CANNON.Body({mass:0,position:new CANNON.Vec3(59,11,120),material:g});b.addShape(f);a.add(b);var E=new CANNON.Box(new CANNON.Vec3(11,.5,.5));f=new CANNON.Body({mass:0,position:new CANNON.Vec3(59,-11,120),material:g});f.addShape(E);a.add(f);E=new CANNON.Box(new CANNON.Vec3(.5,11,.5));var J=new CANNON.Body({mass:0,position:new CANNON.Vec3(70,0,120),material:g});J.addShape(E);a.add(J);b.addEventListener("collide",
function(d){h=!0});f.addEventListener("collide",function(d){h=!0});J.addEventListener("collide",function(d){h=!0});b=new CANNON.Box(new CANNON.Vec3(8,.5,.5));f=new CANNON.Body({mass:0,position:new CANNON.Vec3(59,8,113),material:g});f.addShape(b);a.add(f);b=new CANNON.Box(new CANNON.Vec3(8,.5,.5));f=new CANNON.Body({mass:0,position:new CANNON.Vec3(59,-8,113),material:g});f.addShape(b);a.add(f);b=new CANNON.Box(new CANNON.Vec3(.5,8,.5));g=new CANNON.Body({mass:0,position:new CANNON.Vec3(67,0,113),material:g});
g.addShape(b);a.add(g);for(a=0;36>a;a++)k.push(createBitmap(s_oSpriteLibrary.getSprite("bsk"+(a+1)))),k[a].visible=!1,k[a].x=n[1].x,k[a].y=n[1].y,k[a].scaleX=1.2,k[a].scaleY=1.2,s_oStage.addChild(k[a]);k[0].visible=!0;this.nextScene=function(){l++;this.loadBg(l);for(var d=0;36>d;d++)k[d].x=n[l].x,k[d].y=n[l].y;t.x=u.x=q[l].x;t.y=u.y=q[l].y;5===l&&(t.scaleX=u.scaleX=-1);switch(l){case 2:x.visible=!0;x.x=590;x.y=46;x.setTransform(x.x,x.y,1,1,0,0,-15);break;case 3:x.visible=!0;x.x=525;x.y=50;x.setTransform(x.x,
x.y,1.2,1.2,0,0,0);break;case 4:x.visible=!0;x.x=437;x.y=46;x.setTransform(x.x,x.y,1,1,0,0,15);break;case 5:x.visible=!1}};this.updateTime=function(d){x.text=formatTime(d)};this.updateBasket=function(d){if(r){if(113<d.z&&120>d.z&&48<d.x&&67>d.x&&-8<d.y&&8>d.y)return r=!1,!0;if(!0===h&&!0===r)return h=!1}};this.scored=function(){if(14>c||28<=c&&35>=c)return this.playFrames(0,14,!1),!0;k[c].visible=!1;k[0].visible=!0;c=0;return!1};this.rimCollision=function(){if(35>c)return this.playFrames(28,35,!1),
!0;k[c].visible=!1;k[0].visible=!0;c=0;return!1};this.newBall=function(){h=!1;r=!0;c=0};this.getCartCoords=function(){return{x:u.x+CART_WIDTH/2,y:u.y+CART_HEIGHT/2}};this.loadBg=function(d){var w=3>=d?"field_camera_"+d:4===d?"field_camera_2":"field_camera_1";var z=s_oStage.getChildIndex(C);C=createBitmap(s_oSpriteLibrary.getSprite(w));3>d&&(C.scaleX=-1,C.x=CANVAS_WIDTH);s_oStage.removeChildAt(z);s_oStage.addChildAt(C,z)};this.playFrames=function(d,w,z){c<d||c>w||void 0===c?(k[c]&&(k[c].visible=!1),
c=d,m=k[c].visible=!0):(k[c].visible=!1,c===d&&!1===m?(m=!0,c+=1):c===w?!0===z?c=d:(m=!1,c--):m?c++:c--,k[c].visible=!0)}}
function CPlayer(a,f){var b=!1,g=!1,r=!1,m=!0,h=void 0,c=1,l=[];this.init=function(k){for(var n=0;131>=n;n++)l.push(createBitmap(s_oSpriteLibrary.getSprite("pl"+n))),l[n].visible=!1,l[n].regX=PLAYER_WIDTH/2,l[n].regY=PLAYER_HEIGHT/2,l[n].x=k.x-PLAYER_WIDTH,l[n].y=k.y-.55*PLAYER_HEIGHT,s_oStage.addChild(l[n])};this.nextScene=function(k){c++;this.newBall();if(5>c)for(var n=0;131>=n;n++)l[n].x=k.x-PLAYER_WIDTH,l[n].y=k.y-.55*PLAYER_HEIGHT;else for(n=0;131>=n;n++)l[n].x=k.x+.05*PLAYER_WIDTH,l[n].y=k.y-
.55*PLAYER_HEIGHT,l[n].scaleX=-1};this.idle1=function(){this.playFrames(0,15,!1)};this.grab1=function(){15>h?this.playFrames(0,15,!0):38>=h?(35===h&&(b=!0),this.playFrames(16,39,!0)):39===h&&!1===g&&(g=!0,a.ballWaitToThrow(),createjs.Tween.get(l[h]).to({scaleY:.98,y:f.y-.55*PLAYER_HEIGHT+5},450,createjs.Ease.linear).call(function(){createjs.Tween.get(l[h]).to({scaleY:1,y:f.y-.55*PLAYER_HEIGHT},450,createjs.Ease.linear).call(function(){g=!1})}))};this.grab2=function(){!b||!0===b&&61>h?(this.playFrames(44,
61,!0),57===h&&(b=!0)):!0===b&&61<=h&&!1===g&&(g=!0,a.ballWaitToThrow(),createjs.Tween.removeTweens(l[h]),createjs.Tween.get(l[h]).to({scaleY:.98,y:f.y-.55*PLAYER_HEIGHT+5},450,createjs.Ease.linear).call(function(){createjs.Tween.get(l[h]).to({scaleY:1,y:f.y-.55*PLAYER_HEIGHT},450,createjs.Ease.linear).call(function(){g=!1})}))};this.throwing=function(){if(43>h)this.playFrames(40,43,!0);else return!0};this.endTurn=function(){r?this.idle1():(this.playFrames(86,131,!0),131===h&&(r=!0))};this.playFrames=
function(k,n,q){h<k||h>n||void 0===h?(l[h]&&(l[h].visible=!1),h=k,m=l[h].visible=!0):(l[h].visible=!1,h===k&&!1===m?(m=!0,h+=1):h===n?!0===q?h=k:(m=!1,h--):m?h++:h--,l[h].visible=!0)};this.getPlCoords=function(){return{x:l[39].x-PLAYER_WIDTH/8,y:l[39].y-PLAYER_HEIGHT/10-BALL_SIZE/2}};this.isBallGrabbed=function(){return b};this.newBall=function(){r=g=b=!1};this.init(f)}
function CEndPanel(a,f,b,g){var r,m,h,c,l,k,n,q;this._init=function(C,x,t,u){r=u;h=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));m=h.on("click",function(){});s_oStage.addChild(h);c=new CTLText(s_oStage,CANVAS_WIDTH/2-250,205,500,52,52,"center","#FFCC00",FONT_GAME,1,0,0,TEXT_FINALSCORE+" "+x,!0,!0,!1,!1);c.setAlpha(0);c.setShadow("#000000",4,4,3);createjs.Tween.get(c.getText()).to({x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-130,alpha:1},1600,createjs.Ease.quadOut);l=new CTLText(s_oStage,CANVAS_WIDTH/
2-250,CANVAS_HEIGHT/2-85,500,52,36,"center","#FFCC00",FONT_GAME,1,0,0,TEXT_FINALSHOTS+" "+t,!0,!0,!1,!1);l.setAlpha(0);l.setShadow("#000000",3,3,3);createjs.Tween.get(l.getText()).wait(500).to({alpha:1},500,createjs.Ease.quadOut);C=0>=C?0:formatTime(C);k=new CTLText(s_oStage,CANVAS_WIDTH/2-250,CANVAS_HEIGHT/2-30,500,52,36,"center","#FFCC00",FONT_GAME,1,0,0,TEXT_FINALTIME+" "+C,!0,!0,!1,!1);k.setAlpha(0);k.setShadow("#000000",3,3,3);createjs.Tween.get(k.getText()).wait(750).to({alpha:1},500,createjs.Ease.quadOut);
C=0===t?0:(x/t*100).toFixed(1);n=new CTLText(s_oStage,CANVAS_WIDTH/2-250,CANVAS_HEIGHT/2+25,500,52,36,"center","#FFCC00",FONT_GAME,1,0,0,TEXT_FINALSUCCESSPERC+" "+C+"%",!0,!0,!1,!1);n.setAlpha(0);n.setShadow("#000000",3,3,3);var E=this;createjs.Tween.get(n.getText()).wait(1E3).to({alpha:1},500,createjs.Ease.quadOut).call(function(){var J=s_oSpriteLibrary.getSprite("but_play");q=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+125,J,TEXT_PLAYAGAIN,FONT_GAME,"#ffffff",30,s_oStage);q.addEventListener(ON_MOUSE_UP,
E._onButPlayAgain,E)},E);$(s_oMain).trigger("save_score",x);$(s_oMain).trigger("end_level")};this.unload=function(){h.off("click",m);q.unload();q=null};this._onButPlayAgain=function(){r.unload()};this._init(a,f,b,g)}
function CCreditsPanel(){var a,f,b,g,r,m,h,c,l;this._init=function(){c=new createjs.Container;s_oStage.addChild(c);var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));c.addChild(k);r=new createjs.Shape;r.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.addChild(r);k=s_oSpriteLibrary.getSprite("msg_box");f=createBitmap(k);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;f.regX=k.width/2;f.regY=k.height/2;c.addChild(f);m=new createjs.Shape;m.graphics.beginFill("#0f0f0f").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=.01;l=m.on("click",function(){});c.addChild(m);k=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH/2+244;b=new CGfxButton(a,254,k,c);b.addEventListener(ON_MOUSE_UP,this.unload,this);g=new createjs.Text(TEXT_CREDITS_DEVELOPED,"36px "+FONT_GAME,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=290;g.textAlign="center";c.addChild(g);k=s_oSpriteLibrary.getSprite("logo_credits");var n=createBitmap(k);n.regX=k.width/2;n.regY=k.height/2;n.x=CANVAS_WIDTH/2;n.y=390;c.addChild(n);
h=new createjs.Text("www.codethislab.com","36px "+FONT_GAME,"#ffffff");h.x=CANVAS_WIDTH/2;h.y=450;h.textAlign="center";c.addChild(h);k=new createjs.Text("v2","12px "+FONT_GAME,"#ffffff");k.x=CANVAS_WIDTH/2-270;k.y=540;k.textAlign="center";c.addChild(k)};this.unload=function(){m.off("click",l);b.unload();b=null;s_oStage.removeChild(c)};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,f,b,g){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,f,b,g))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,f,b,g,r,m,h,c,l,k,n,q,C,x,t,u,E){this._oContainer=a;this._x=f;this._y=b;this._iWidth=g;this._iHeight=r;this._bMultiline=u;this._iFontSize=m;this._szAlign=h;this._szColor=c;this._szFont=l;this._iPaddingH=n;this._iPaddingV=q;this._bVerticalAlign=t;this._bFitText=x;this._bDebug=E;this._oDebugShape=null;this._fLineHeightFactor=k;this._oText=null;C&&this.__createText(C)};