const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.GD_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Sprite.Exps.ImagePointCount,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.Angle,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Physics.Cnds.IsSleeping,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Behaviors.Physics.Exps.LinearDamping,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Pin.Exps.PinnedUID,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer
	];
};
self.C3_JsPropNameTable = [
	{Background_Green: 0},
	{Touch: 0},
	{Builder_Background01: 0},
	{Coins: 0},
	{Builder02: 0},
	{Portal_Visual: 0},
	{Boxing_Punch: 0},
	{Pin: 0},
	{Timer: 0},
	{Ball_Indicator: 0},
	{Impulses: 0},
	{Particles_Color1: 0},
	{Particles_Color2: 0},
	{Particles_Color3: 0},
	{Particles_Color4: 0},
	{Hole: 0},
	{Touch_Area: 0},
	{Target_Control: 0},
	{Target_Indicator_Spawn: 0},
	{Distance_Control: 0},
	{value: 0},
	{Target_Indicator: 0},
	{Show_Target_Indicator: 0},
	{check_button: 0},
	{Cancel_Button: 0},
	{Rotate: 0},
	{Touch_Indicator: 0},
	{manual_settings: 0},
	{punch_angle: 0},
	{Physics: 0},
	{Boxing_Glove: 0},
	{Spike_Bar: 0},
	{Fade: 0},
	{Effect_Ball_Explosion: 0},
	{Effect_Coins_Collect: 0},
	{sameID: 0},
	{Coins_Shadow: 0},
	{Effect_Smoke_Trail: 0},
	{Portal_Light: 0},
	{Cannon: 0},
	{belong_to_the_group: 0},
	{activated: 0},
	{speed: 0},
	{Burners: 0},
	{Sine: 0},
	{Play_Button: 0},
	{LocalStorage: 0},
	{Loading_Bar_Background: 0},
	{Loading_Bar: 0},
	{Loadin_Text: 0},
	{Audio_Button: 0},
	{angle_direction: 0},
	{portal_ID: 0},
	{portal_activated: 0},
	{Portal: 0},
	{ball_speed: 0},
	{ball_angle: 0},
	{input_angle: 0},
	{output_angle: 0},
	{move_to_portal: 0},
	{cannon: 0},
	{ball_activated: 0},
	{dead_animation: 0},
	{Ball: 0},
	{Effect_Ball_Trail: 0},
	{Sand: 0},
	{Bullet: 0},
	{Movement_Blocks: 0},
	{count_times: 0},
	{Flag: 0},
	{Coins_Icon: 0},
	{Pause_Button: 0},
	{Hole_Expand: 0},
	{Cannon_Target_Spawn: 0},
	{Cannon_Target_Indicator: 0},
	{type_of_block: 0},
	{Movement_Map: 0},
	{direction: 0},
	{Image_Point: 0},
	{max_ImagePoint: 0},
	{block_ID: 0},
	{New_Position: 0},
	{Water_Tiles: 0},
	{Color_Transition: 0},
	{Information_Text: 0},
	{time_down: 0},
	{time_up: 0},
	{Mole_Hole: 0},
	{Collision_Mask: 0},
	{Effect_Cannon_Explosion: 0},
	{Ball_Shadow: 0},
	{Hill: 0},
	{Hill_Overlay: 0},
	{Hill_Left_Recoil: 0},
	{Hill_Right_Recoil: 0},
	{active: 0},
	{checked: 0},
	{reset: 0},
	{Hill_Set_Curve: 0},
	{Sine2: 0},
	{Exit_Button_Menu: 0},
	{Value: 0},
	{Restart_Button: 0},
	{Information_Background: 0},
	{Audio: 0},
	{Coins_TextGreen: 0},
	{Score_TextGreen: 0},
	{BestScore_TextGreen: 0},
	{Cannon_Shadow: 0},
	{Builder01: 0},
	{Builder_Background02: 0},
	{Block_Style: 0},
	{Flag_Shadow: 0},
	{Screen_Background: 0},
	{reset_position: 0},
	{Vegetation: 0},
	{Exit_Button_Pause: 0},
	{Screen_TItle: 0},
	{Screen_Overlay: 0},
	{UI_Flag: 0},
	{UI_Ball: 0},
	{reset_Position: 0},
	{Vegetation_Shadow: 0},
	{Menu_Backgroud: 0},
	{Menu_Overlay_Background: 0},
	{Menu_Vegetation: 0},
	{Menu_Clouds: 0},
	{GameTitle: 0},
	{Menu_Mill: 0},
	{Mill_Propeller: 0},
	{Mill_Propeller_Shadow: 0},
	{Game_Version_Text: 0},
	{UI_Title_Flag: 0},
	{GameTitle_Background: 0},
	{Buttons_Background: 0},
	{Loading_Bar_Ball: 0},
	{Solid: 0},
	{Loading_Bar_Overlap: 0},
	{Particles_Color5: 0},
	{Loading_Bar_Flag: 0},
	{Hand_Movement: 0},
	{Hand_Opacity: 0},
	{Tutorial_Element_Hand: 0},
	{Text_Animation: 0},
	{Tutorial_Element_Text: 0},
	{Indicator_Opacity: 0},
	{Tutorial_Element_Indicator: 0},
	{Background_Blue: 0},
	{Builder05: 0},
	{Score_TextBlue: 0},
	{BestScore_TextBlue: 0},
	{Coins_TextBlue: 0},
	{Guide_Background: 0},
	{Mill: 0},
	{Mill_Shadow: 0},
	{Lighthouse_Floor: 0},
	{Water_Tiles_Deck: 0},
	{Builder04: 0},
	{Green_Overlap: 0},
	{Effect_Ball_Collision: 0},
	{Effect_Smoke_Explosion: 0},
	{ScrollTo: 0},
	{Shake_Screen: 0},
	{Impulses_Shadow: 0},
	{Sand_Shadow: 0},
	{Burners_Shadow: 0},
	{Builder03: 0},
	{Blue_Overlap: 0},
	{Builder06: 0},
	{startY: 0},
	{Time: 0},
	{Duration: 0},
	{Scroll_Screen: 0},
	{Help_Information: 0},
	{watch_ads: 0},
	{GameDistributionSDK: 0},
	{Default_Levels: 0},
	{Bonus_Level: 0},
	{Set_Ball_Speed: 0},
	{Score: 0},
	{BestScore: 0},
	{Life: 0},
	{Moving_Ball: 0},
	{Active_Burners_Group: 0},
	{First_Time_Playing: 0},
	{Counting_Levels: 0},
	{Levels_Played: 0},
	{Go_To_Level: 0}
];

self.InstanceType = {
	Background_Green: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Builder_Background01: class extends self.ITiledBackgroundInstance {},
	Coins: class extends self.ISpriteInstance {},
	Builder02: class extends self.ITiledBackgroundInstance {},
	Portal_Visual: class extends self.ISpriteInstance {},
	Boxing_Punch: class extends self.ISpriteInstance {},
	Ball_Indicator: class extends self.ISpriteInstance {},
	Impulses: class extends self.ISpriteInstance {},
	Particles_Color1: class extends self.IParticlesInstance {},
	Particles_Color2: class extends self.IParticlesInstance {},
	Particles_Color3: class extends self.IParticlesInstance {},
	Particles_Color4: class extends self.IParticlesInstance {},
	Hole: class extends self.ISpriteInstance {},
	Touch_Area: class extends self.ISpriteInstance {},
	Target_Control: class extends self.ISpriteInstance {},
	Target_Indicator_Spawn: class extends self.ISpriteInstance {},
	Distance_Control: class extends self.ITiledBackgroundInstance {},
	Target_Indicator: class extends self.ISpriteInstance {},
	Show_Target_Indicator: class extends self.ITiledBackgroundInstance {},
	Cancel_Button: class extends self.ISpriteInstance {},
	Touch_Indicator: class extends self.ISpriteInstance {},
	Boxing_Glove: class extends self.ISpriteInstance {},
	Spike_Bar: class extends self.ITiledBackgroundInstance {},
	Effect_Ball_Explosion: class extends self.ISpriteInstance {},
	Effect_Coins_Collect: class extends self.ISpriteInstance {},
	Coins_Shadow: class extends self.ISpriteInstance {},
	Effect_Smoke_Trail: class extends self.ISpriteInstance {},
	Portal_Light: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	Burners: class extends self.ISpriteInstance {},
	Play_Button: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Loading_Bar_Background: class extends self.ISpriteInstance {},
	Loading_Bar: class extends self.ITiledBackgroundInstance {},
	Loadin_Text: class extends self.ISpriteInstance {},
	Audio_Button: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Effect_Ball_Trail: class extends self.ISpriteInstance {},
	Sand: class extends self.ISpriteInstance {},
	Movement_Blocks: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	Coins_Icon: class extends self.ISpriteInstance {},
	Pause_Button: class extends self.ISpriteInstance {},
	Hole_Expand: class extends self.ISpriteInstance {},
	Cannon_Target_Spawn: class extends self.ISpriteInstance {},
	Cannon_Target_Indicator: class extends self.ISpriteInstance {},
	Movement_Map: class extends self.ISpriteInstance {},
	New_Position: class extends self.ISpriteInstance {},
	Water_Tiles: class extends self.ISpriteInstance {},
	Color_Transition: class extends self.ISpriteInstance {},
	Information_Text: class extends self.ITextInstance {},
	Mole_Hole: class extends self.ISpriteInstance {},
	Collision_Mask: class extends self.ITiledBackgroundInstance {},
	Effect_Cannon_Explosion: class extends self.ISpriteInstance {},
	Ball_Shadow: class extends self.ISpriteInstance {},
	Hill: class extends self.ISpriteInstance {},
	Hill_Overlay: class extends self.ISpriteInstance {},
	Hill_Left_Recoil: class extends self.ISpriteInstance {},
	Hill_Right_Recoil: class extends self.ISpriteInstance {},
	Hill_Set_Curve: class extends self.ISpriteInstance {},
	Exit_Button_Menu: class extends self.ISpriteInstance {},
	Restart_Button: class extends self.ISpriteInstance {},
	Information_Background: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Coins_TextGreen: class extends self.ISpriteFontInstance {},
	Score_TextGreen: class extends self.ISpriteFontInstance {},
	BestScore_TextGreen: class extends self.ISpriteFontInstance {},
	Cannon_Shadow: class extends self.ISpriteInstance {},
	Builder01: class extends self.ISpriteInstance {},
	Builder_Background02: class extends self.ITiledBackgroundInstance {},
	Block_Style: class extends self.ISpriteInstance {},
	Flag_Shadow: class extends self.ISpriteInstance {},
	Screen_Background: class extends self.ISpriteInstance {},
	Vegetation: class extends self.ITiledBackgroundInstance {},
	Exit_Button_Pause: class extends self.ISpriteInstance {},
	Screen_TItle: class extends self.ISpriteInstance {},
	Screen_Overlay: class extends self.ITiledBackgroundInstance {},
	UI_Flag: class extends self.ISpriteInstance {},
	UI_Ball: class extends self.ISpriteInstance {},
	Vegetation_Shadow: class extends self.ITiledBackgroundInstance {},
	Menu_Backgroud: class extends self.ITiledBackgroundInstance {},
	Menu_Overlay_Background: class extends self.ISpriteInstance {},
	Menu_Vegetation: class extends self.ITiledBackgroundInstance {},
	Menu_Clouds: class extends self.ITiledBackgroundInstance {},
	GameTitle: class extends self.ISpriteInstance {},
	Menu_Mill: class extends self.ISpriteInstance {},
	Mill_Propeller: class extends self.ISpriteInstance {},
	Mill_Propeller_Shadow: class extends self.ISpriteInstance {},
	Game_Version_Text: class extends self.ISpriteInstance {},
	UI_Title_Flag: class extends self.ISpriteInstance {},
	GameTitle_Background: class extends self.ISpriteInstance {},
	Buttons_Background: class extends self.ISpriteInstance {},
	Loading_Bar_Ball: class extends self.ISpriteInstance {},
	Loading_Bar_Overlap: class extends self.ISpriteInstance {},
	Particles_Color5: class extends self.IParticlesInstance {},
	Loading_Bar_Flag: class extends self.ISpriteInstance {},
	Tutorial_Element_Hand: class extends self.ISpriteInstance {},
	Tutorial_Element_Text: class extends self.ISpriteInstance {},
	Tutorial_Element_Indicator: class extends self.ISpriteInstance {},
	Background_Blue: class extends self.ITiledBackgroundInstance {},
	Builder05: class extends self.ISpriteInstance {},
	Score_TextBlue: class extends self.ISpriteFontInstance {},
	BestScore_TextBlue: class extends self.ISpriteFontInstance {},
	Coins_TextBlue: class extends self.ISpriteFontInstance {},
	Guide_Background: class extends self.ITiledBackgroundInstance {},
	Mill: class extends self.ISpriteInstance {},
	Mill_Shadow: class extends self.ISpriteInstance {},
	Lighthouse_Floor: class extends self.ISpriteInstance {},
	Water_Tiles_Deck: class extends self.ISpriteInstance {},
	Builder04: class extends self.ISpriteInstance {},
	Green_Overlap: class extends self.ITiledBackgroundInstance {},
	Effect_Ball_Collision: class extends self.ISpriteInstance {},
	Effect_Smoke_Explosion: class extends self.ISpriteInstance {},
	Shake_Screen: class extends self.ISpriteInstance {},
	Impulses_Shadow: class extends self.ITiledBackgroundInstance {},
	Sand_Shadow: class extends self.ITiledBackgroundInstance {},
	Burners_Shadow: class extends self.ITiledBackgroundInstance {},
	Builder03: class extends self.ISpriteInstance {},
	Blue_Overlap: class extends self.ITiledBackgroundInstance {},
	Builder06: class extends self.ISpriteInstance {},
	Scroll_Screen: class extends self.ISpriteInstance {},
	Help_Information: class extends self.ITextInstance {},
	watch_ads: class extends self.ISpriteInstance {},
	GameDistributionSDK: class extends self.IInstance {}
}